<?php
$centros_formacion = array(
  array('id' => '1','nombre' => 'CENTRO ACUICOLA Y AGROINDUSTRIAL DE GAIRA','regional' => 'MAGDALENA'),
  array('id' => '2','nombre' => 'CENTRO AGROECOLOGICO Y EMPRESARIAL','regional' => 'CUNDINAMARCA'),
  array('id' => '3','nombre' => 'CENTRO AGROEMPRESARIAL','regional' => 'CESAR'),
  array('id' => '4','nombre' => 'CENTRO AGROEMPRESARIAL Y ACUICOLA','regional' => 'GUAJIRA'),
  array('id' => '5','nombre' => 'CENTRO AGROEMPRESARIAL Y DESARROLLO PECUARIO DEL HUILA','regional' => 'HUILA'),
  array('id' => '6','nombre' => 'CENTRO AGROEMPRESARIAL Y MINERO','regional' => 'BOLIVAR'),
  array('id' => '7','nombre' => 'CENTRO AGROEMPRESARIAL Y TURISTICO DE LOS ANDES','regional' => 'SANTANDER'),
  array('id' => '8','nombre' => 'CENTRO AGROFORESTAL Y ACUICOLA ARAPAIMA','regional' => 'PUTUMAYO'),
  array('id' => '9','nombre' => 'CENTRO AGROINDUSTRIAL','regional' => 'QUINDIO'),
  array('id' => '10','nombre' => 'CENTRO AGROINDUSTRIAL DEL META','regional' => 'META'),
  array('id' => '11','nombre' => 'CENTRO AGROINDUSTRIAL Y FORTALECIMIENTO EMPRESARIAL DE CASANARE','regional' => 'CASANARE'),
  array('id' => '12','nombre' => 'CENTRO AGROINDUSTRIAL Y PESQUERO DE LA COSTA PACIFICA','regional' => 'NARIÑO'),
  array('id' => '13','nombre' => 'CENTRO AGROPECUARIO','regional' => 'CAUCA'),
  array('id' => '14','nombre' => 'CENTRO AGROPECUARIO DE BUGA','regional' => 'VALLE'),
  array('id' => '15','nombre' => 'CENTRO AGROPECUARIO LA GRANJA','regional' => 'TOLIMA'),
  array('id' => '16','nombre' => 'CENTRO AGROPECUARIO Y DE BIOTECNOLOGIA EL PORVENIR','regional' => 'CORDOBA'),
  array('id' => '17','nombre' => 'CENTRO AGROPECUARIO Y DE SERVICIOS AMBIENTALES JIRI - JIRIMO','regional' => 'VAUPES'),
  array('id' => '18','nombre' => 'CENTRO AGROTURISTICO','regional' => 'SANTANDER'),
  array('id' => '19','nombre' => 'CENTRO AMBIENTAL Y ECOTURISTICO DEL NORORIENTE AMAZONICO','regional' => 'GUAINIA'),
  array('id' => '20','nombre' => 'CENTRO ATENCION SECTOR AGROPECUARIO','regional' => 'SANTANDER'),
  array('id' => '21','nombre' => 'CENTRO ATENCION SECTOR AGROPECUARIO','regional' => 'RISARALDA'),
  array('id' => '22','nombre' => 'CENTRO BIOTECNOLOGICO DEL CARIBE','regional' => 'CESAR'),
  array('id' => '23','nombre' => 'CENTRO DE AUTOMATIZACION INDUSTRIAL','regional' => 'CALDAS'),
  array('id' => '24','nombre' => 'CENTRO DE BIOTECNOLOGIA AGROPECUARIA','regional' => 'CUNDINAMARCA'),
  array('id' => '25','nombre' => 'CENTRO DE BIOTECNOLOGIA INDUSTRIAL','regional' => 'VALLE'),
  array('id' => '26','nombre' => 'CENTRO DE COMERCIO','regional' => 'ANTIOQUIA'),
  array('id' => '27','nombre' => 'CENTRO DE COMERCIO Y SERVICIOS','regional' => 'TOLIMA'),
  array('id' => '28','nombre' => 'CENTRO DE COMERCIO Y TURISMO','regional' => 'QUINDIO'),
  array('id' => '29','nombre' => 'CENTRO DE COMERCIO INDUSTRIA Y TURISMO DE CORDOBA','regional' => 'CORDOBA'),
  array('id' => '30','nombre' => 'CENTRO DE DESARROLLO AGROEMPRESARIAL','regional' => 'CUNDINAMARCA'),
  array('id' => '31','nombre' => 'CENTRO DE DESARROLLO AGROEMPRESARIAL Y TURISTICO DEL HUILA','regional' => 'HUILA'),
  array('id' => '32','nombre' => 'CENTRO DE DESARROLLO AGROINDUSTRIAL Y EMPRESARIAL','regional' => 'CUNDINAMARCA'),
  array('id' => '33','nombre' => 'CENTRO DE DESARROLLO AGROINDUSTRIAL','regional' => ' TURISTICO Y TECNOLOGICO DEL GUAVIARE'),
  array('id' => '34','nombre' => 'CENTRO DE DESARROLLO AGROPECUARIO Y AGROINDUSTRIAL','regional' => 'BOYACA'),
  array('id' => '35','nombre' => 'CENTRO DE DISEÑO E INNOVACION TECNOLOGICA INDUSTRIAL','regional' => 'RISARALDA'),
  array('id' => '36','nombre' => 'CENTRO DE DISEÑO TECNOLOGICO INDUSTRIAL','regional' => 'VALLE'),
  array('id' => '37','nombre' => 'CENTRO DE DISEÑO Y METROLOGIA','regional' => 'DISTRITO CAPITAL'),
  array('id' => '38','nombre' => 'CENTRO DE ELECTRICIDAD Y AUTOMATIZACION INDUSTRIAL - CEAI','regional' => 'VALLE'),
  array('id' => '39','nombre' => 'CENTRO DE ELECTRICIDAD ELECTRONICA Y TELECOMUNICACIONES','regional' => 'DISTRITO CAPITAL'),
  array('id' => '40','nombre' => 'CENTRO DE FORMACION AGROINDUSTRIAL','regional' => 'HUILA'),
  array('id' => '41','nombre' => 'CENTRO DE FORMACION DE TALENTO HUMANO EN SALUD','regional' => 'DISTRITO CAPITAL'),
  array('id' => '42','nombre' => 'CENTRO DE FORMACION EN ACTIVIDAD FISICA Y CULTURA','regional' => 'DISTRITO CAPITAL'),
  array('id' => '43','nombre' => 'CENTRO DE FORMACION EN DISEÑO CONFECCION Y MODA.','regional' => 'ANTIOQUIA'),
  array('id' => '44','nombre' => 'CENTRO DE FORMACION MINERO AMBIENTAL','regional' => 'ANTIOQUIA'),
  array('id' => '45','nombre' => 'CENTRO DE FORMACION PARA EL DESARROLLO RURAL Y MINERO','regional' => 'NORTE DE SANTANDER'),
  array('id' => '46','nombre' => 'CENTRO DE FORMACION TURISTICA GENTE DE MAR Y DE SERVICIOS','regional' => 'SAN ANDRES'),
  array('id' => '47','nombre' => 'CENTRO DE GESTION ADMINISTRATIVA','regional' => 'DISTRITO CAPITAL'),
  array('id' => '48','nombre' => 'CENTRO DE GESTION ADMINISTRATIVA Y FORTALECIMIENTO EMPRESARIAL','regional' => 'BOYACA'),
  array('id' => '49','nombre' => 'CENTRO DE GESTION AGROEMPRESARIAL DEL ORIENTE','regional' => 'SANTANDER'),
  array('id' => '50','nombre' => 'CENTRO DE GESTION DE MERCADOS LOGISTICA Y TECNOLOGIAS DE LA INFORMACION','regional' => 'DISTRITO CAPITAL'),
  array('id' => '51','nombre' => 'CENTRO DE GESTION INDUSTRIAL','regional' => 'DISTRITO CAPITAL'),
  array('id' => '52','nombre' => 'CENTRO DE GESTION TECNOLOGICA DE SERVICIOS','regional' => 'VALLE'),
  array('id' => '53','nombre' => 'CENTRO DE GESTION Y DESARROLLO AGROINDUSTRIAL DE ARAUCA','regional' => 'ARAUCA'),
  array('id' => '54','nombre' => 'CENTRO DE GESTION Y DESARROLLO SOSTENIBLE SURCOLOMBIANO','regional' => 'HUILA'),
  array('id' => '55','nombre' => 'CENTRO DE INDUSTRIA Y CONSTRUCCION','regional' => 'TOLIMA'),
  array('id' => '56','nombre' => 'CENTRO DE INDUSTRIA Y SERVICIOS DEL META','regional' => 'META'),
  array('id' => '57','nombre' => 'CENTRO DE LA CONSTRUCCION','regional' => 'VALLE'),
  array('id' => '58','nombre' => 'CENTRO DE LA INDUSTRIA LA EMPRESA Y LOS SERVICIOS','regional' => 'HUILA'),
  array('id' => '59','nombre' => 'CENTRO DE LA INDUSTRIA LA EMPRESA Y LOS SERVICIOS ','regional' => 'NORTE DE SANTANDER'),
  array('id' => '60','nombre' => 'CENTRO DE LA INNOVACION LA AGROINDUSTRIA Y LA AVIACION','regional' => 'ANTIOQUIA'),
  array('id' => '61','nombre' => 'CENTRO DE LA INNOVACION LA TECNOLOGIA Y LOS SERVICIOS','regional' => 'SUCRE'),
  array('id' => '62','nombre' => 'CENTRO DE LA TECNOLOGIA DEL DISEÑO Y LA PRODUCTIVIDAD EMPRESARIAL','regional' => 'CUNDINAMARCA'),
  array('id' => '63','nombre' => 'CENTRO DE LOGISTICA Y PROMOCION ECOTURISTICA DEL MAGDALENA','regional' => 'MAGDALENA'),
  array('id' => '64','nombre' => 'CENTRO DE LOS RECURSOS NATURALES RENOVABLES LA SALADA','regional' => 'ANTIOQUIA'),
  array('id' => '65','nombre' => 'CENTRO DE MANUFACTURA EN TEXTILES Y CUERO','regional' => 'DISTRITO CAPITAL'),
  array('id' => '66','nombre' => 'CENTRO DE MATERIALES Y ENSAYOS','regional' => 'DISTRITO CAPITAL'),
  array('id' => '67','nombre' => 'CENTRO DE OPERACION Y MANTENIMIENTO MINERO','regional' => 'CESAR'),
  array('id' => '68','nombre' => 'CENTRO DE PROCESOS INDUSTRIALES Y CONSTRUCCION','regional' => 'CALDAS'),
  array('id' => '69','nombre' => 'CENTRO DE PRODUCCION Y TRANSFORMACION AGROINDUSTRIAL DE LA ORINOQUIA','regional' => 'VICHADA'),
  array('id' => '70','nombre' => 'CENTRO DE RECURSOS NATURALES - INDUSTRIA Y BIODIVERSIDAD','regional' => 'CHOCO'),
  array('id' => '71','nombre' => 'CENTRO DE SERVICIOS DE SALUD','regional' => 'ANTIOQUIA'),
  array('id' => '72','nombre' => 'CENTRO DE SERVICIOS EMPRESARIALES Y TURISTICOS','regional' => 'SANTANDER'),
  array('id' => '73','nombre' => 'CENTRO DE SERVICIOS FINANCIEROS','regional' => 'DISTRITO CAPITAL'),
  array('id' => '74','nombre' => 'CENTRO DE SERVICIOS Y GESTION EMPRESARIAL ','regional' => 'ANTIOQUIA; ;'),
  array('id' => '75','nombre' => 'CENTRO DE TECNOLOGIA DE LA MANUFACTURA AVANZADA.','regional' => 'ANTIOQUIA'),
  array('id' => '76','nombre' => 'CENTRO DE TECNOLOGIAS AGROINDUSTRIALES','regional' => 'VALLE'),
  array('id' => '77','nombre' => 'CENTRO DE TECNOLOGIAS DEL TRANSPORTE','regional' => 'DISTRITO CAPITAL; ; '),
  array('id' => '78','nombre' => 'CENTRO DE TECNOLOGIAS PARA LA CONSTRUCCION Y LA MADERA','regional' => 'DISTRITO CAPITAL'),
  array('id' => '79','nombre' => 'CENTRO DE TELEINFORMATICA Y PRODUCCION INDUSTRIAL','regional' => 'CAUCA'),
  array('id' => '80','nombre' => 'CENTRO DEL DISEÑO Y MANUFACTURA DEL CUERO','regional' => 'ANTIOQUIA'),
  array('id' => '81','nombre' => 'CENTRO INDUSTRIAL DE MANTENIMIENTO INTEGRAL','regional' => 'SANTANDER'),
  array('id' => '82','nombre' => 'CENTRO INDUSTRIAL DE MANTENIMIENTO Y MANUFACTURA','regional' => 'BOYACA'),
  array('id' => '83','nombre' => 'CENTRO INDUSTRIAL DEL DISEÑO Y LA MANUFACTURA','regional' => 'SANTANDER'),
  array('id' => '84','nombre' => 'CENTRO INDUSTRIAL Y DE AVIACION','regional' => 'ATLANTICO'),
  array('id' => '85','nombre' => 'CENTRO INDUSTRIAL Y DE DESARROLLO EMPRESARIAL DE SOACHA','regional' => 'CUNDINAMARCA'),
  array('id' => '86','nombre' => 'CENTRO INDUSTRIAL Y DE ENERGIAS ALTERNATIVAS','regional' => 'GUAJIRA'),
  array('id' => '87','nombre' => 'CENTRO INDUSTRIAL Y DEL DESARROLLO TECNOLOGICO','regional' => 'SANTANDER'),
  array('id' => '88','nombre' => 'CENTRO INTERNACIONAL DE PRODUCCION LIMPIA - LOPE','regional' => 'NARIÑO'),
  array('id' => '89','nombre' => 'CENTRO INTERNACIONAL NAUTICO FLUVIAL Y PORTUARIO','regional' => 'BOLIVAR'),
  array('id' => '90','nombre' => 'CENTRO LATINOAMERICANO DE ESPECIES MENORES','regional' => 'VALLE'),
  array('id' => '91','nombre' => 'CENTRO METALMECANICO','regional' => 'DISTRITO CAPITAL'),
  array('id' => '92','nombre' => 'CENTRO MINERO','regional' => 'BOYACA'),
  array('id' => '93','nombre' => 'CENTRO NACIONAL COLOMBO ALEMAN','regional' => 'ATLANTICO'),
  array('id' => '94','nombre' => 'CENTRO NACIONAL DE ASISTENCIA TECNICA A LA INDUSTRIA  ASTIN','regional' => 'VALLE'),
  array('id' => '95','nombre' => 'CENTRO NACIONAL DE HOTELERIA TURISMO Y ALIMENTOS','regional' => 'DISTRITO CAPITAL'),
  array('id' => '96','nombre' => 'CENTRO NAUTICO PESQUERO DE BUENAVENTURA','regional' => 'VALLE'),
  array('id' => '97','nombre' => 'CENTRO PARA EL DESARROLLO AGROECOLOGICO Y AGROINDUSTRIAL','regional' => 'ATLANTICO'),
  array('id' => '98','nombre' => 'CENTRO PARA EL DESARROLLO DEL HABITAT Y LA CONSTRUCCION','regional' => 'ANTIOQUIA'),
  array('id' => '99','nombre' => 'CENTRO PARA EL DESARROLLO TECNOLOGICO DE LA CONSTRUCCION Y LA INDUSTRIA','regional' => 'QUINDIO'),
  array('id' => '100','nombre' => 'CENTRO PARA LA BIODIVERSIDAD Y EL TURISMO DEL AMAZONAS','regional' => 'AMAZONAS'),
  array('id' => '101','nombre' => 'CENTRO PARA LA FORMACION CAFETERA','regional' => 'CALDAS'),
  array('id' => '102','nombre' => 'CENTRO PARA LA INDUSTRIA DE LA COMUNICACION GRAFICA','regional' => 'DISTRITO CAPITAL'),
  array('id' => '103','nombre' => 'CENTRO PARA LA INDUSTRIA PETROQUIMICA','regional' => 'BOLIVAR'),
  array('id' => '104','nombre' => 'CENTRO PECUARIO Y AGROEMPRESARIAL','regional' => 'CALDAS'),
  array('id' => '105','nombre' => 'CENTRO SUR COLOMBIANO DE LOGISTICA INTERNACIONAL','regional' => 'NARIÑO'),
  array('id' => '106','nombre' => 'CENTRO TECNOLOGICO DE LA AMAZONIA','regional' => 'CAQUETA'),
  array('id' => '107','nombre' => 'CENTRO TECNOLOGICO DEL MOBILIARIO','regional' => 'ANTIOQUIA'),
  array('id' => '108','nombre' => 'CENTRO TEXTIL Y DE GESTION INDUSTRIAL','regional' => 'ANTIOQUIA'),
  array('id' => '109','nombre' => 'COMPLEJO TECNOLOGICO AGROINDUSTRIAL - PECUARIO Y TURISTICO','regional' => 'ANTIOQUIA'),
  array('id' => '110','nombre' => 'COMPLEJO TECNOLOGICO MINERO AGROEMPRESARIAL','regional' => 'ANTIOQUIA'),
  array('id' => '111','nombre' => 'COMPLEJO TECNOLOGICO PARA LA GESTION AGROEMPRESARIAL','regional' => 'ANTIOQUIA'),
  array('id' => '112','nombre' => 'COMPLEJO TECNOLOGICO TURISTICO Y AGROINDUSTRIAL DEL OCCIDENTE ANTIOQUEÑO','regional' => 'ANTIOQUIA')
);


function listarCen(){
   global $centros_formacion;
foreach($centros_formacion as $valor) {    
echo "<option value='".$valor['nombre']." - ".$valor['regional']."'>".$valor['nombre']." - ".$valor['regional']."</option>";
 }
}
