<?php
$ciudad = array(
  array('codigo' => '1','nombre' => 'ABEJORRAL','departamento' => '5'),
  array('codigo' => '2','nombre' => 'ABREGO','departamento' => '54'),
  array('codigo' => '3','nombre' => 'ABRIAQUI','departamento' => '5'),
  array('codigo' => '4','nombre' => 'ACACIAS','departamento' => '50'),
  array('codigo' => '5','nombre' => 'ACANDI','departamento' => '27'),
  array('codigo' => '6','nombre' => 'ACEVEDO','departamento' => '41'),
  array('codigo' => '7','nombre' => 'ACHI','departamento' => '13'),
  array('codigo' => '8','nombre' => 'AGRADO','departamento' => '41'),
  array('codigo' => '9','nombre' => 'AGUA DE DIOS','departamento' => '25'),
  array('codigo' => '10','nombre' => 'AGUACHICA','departamento' => '20'),
  array('codigo' => '11','nombre' => 'AGUADA','departamento' => '68'),
  array('codigo' => '12','nombre' => 'AGUADAS','departamento' => '17'),
  array('codigo' => '13','nombre' => 'AGUAZUL','departamento' => '85'),
  array('codigo' => '14','nombre' => 'AGUSTIN CODAZZI','departamento' => '20'),
  array('codigo' => '15','nombre' => 'AIPE','departamento' => '41'),
  array('codigo' => '16','nombre' => 'ALBAN','departamento' => '25'),
  array('codigo' => '17','nombre' => 'ALBAN','departamento' => '52'),
  array('codigo' => '18','nombre' => 'ALBANIA','departamento' => '18'),
  array('codigo' => '19','nombre' => 'ALBANIA','departamento' => '44'),
  array('codigo' => '20','nombre' => 'ALBANIA','departamento' => '68'),
  array('codigo' => '21','nombre' => 'ALCALA','departamento' => '76'),
  array('codigo' => '22','nombre' => 'ALDANA','departamento' => '52'),
  array('codigo' => '23','nombre' => 'ALEJANDRIA','departamento' => '5'),
  array('codigo' => '24','nombre' => 'ALGARROBO','departamento' => '47'),
  array('codigo' => '25','nombre' => 'ALGECIRAS','departamento' => '41'),
  array('codigo' => '26','nombre' => 'ALMAGUER','departamento' => '19'),
  array('codigo' => '27','nombre' => 'ALMEIDA','departamento' => '15'),
  array('codigo' => '28','nombre' => 'ALPUJARRA','departamento' => '73'),
  array('codigo' => '29','nombre' => 'ALTAMIRA','departamento' => '41'),
  array('codigo' => '30','nombre' => 'ALTO BAUDO','departamento' => '27'),
  array('codigo' => '31','nombre' => 'ALTOS DEL ROSARIO','departamento' => '13'),
  array('codigo' => '32','nombre' => 'ALVARADO','departamento' => '73'),
  array('codigo' => '33','nombre' => 'AMAGA','departamento' => '5'),
  array('codigo' => '34','nombre' => 'AMALFI','departamento' => '5'),
  array('codigo' => '35','nombre' => 'AMBALEMA','departamento' => '73'),
  array('codigo' => '36','nombre' => 'ANAPOIMA','departamento' => '25'),
  array('codigo' => '37','nombre' => 'ANCUYA','departamento' => '52'),
  array('codigo' => '38','nombre' => 'ANDALUCIA','departamento' => '76'),
  array('codigo' => '39','nombre' => 'ANDES','departamento' => '5'),
  array('codigo' => '40','nombre' => 'ANGELOPOLIS','departamento' => '5'),
  array('codigo' => '41','nombre' => 'ANGOSTURA','departamento' => '5'),
  array('codigo' => '42','nombre' => 'ANOLAIMA','departamento' => '25'),
  array('codigo' => '43','nombre' => 'ANORI','departamento' => '5'),
  array('codigo' => '44','nombre' => 'ANSERMA','departamento' => '17'),
  array('codigo' => '45','nombre' => 'ANSERMANUEVO','departamento' => '76'),
  array('codigo' => '46','nombre' => 'ANZA','departamento' => '5'),
  array('codigo' => '47','nombre' => 'ANZOATEGUI','departamento' => '73'),
  array('codigo' => '48','nombre' => 'APARTADO','departamento' => '5'),
  array('codigo' => '49','nombre' => 'APIA','departamento' => '66'),
  array('codigo' => '50','nombre' => 'APULO','departamento' => '25'),
  array('codigo' => '51','nombre' => 'AQUITANIA','departamento' => '15'),
  array('codigo' => '52','nombre' => 'ARACATACA','departamento' => '47'),
  array('codigo' => '53','nombre' => 'ARANZAZU','departamento' => '17'),
  array('codigo' => '54','nombre' => 'ARATOCA','departamento' => '68'),
  array('codigo' => '55','nombre' => 'ARAUCA','departamento' => '81'),
  array('codigo' => '56','nombre' => 'ARAUQUITA','departamento' => '81'),
  array('codigo' => '57','nombre' => 'ARBELAEZ','departamento' => '25'),
  array('codigo' => '58','nombre' => 'ARBOLEDA','departamento' => '52'),
  array('codigo' => '59','nombre' => 'ARBOLEDAS','departamento' => '54'),
  array('codigo' => '60','nombre' => 'ARBOLETES','departamento' => '5'),
  array('codigo' => '61','nombre' => 'ARCABUCO','departamento' => '15'),
  array('codigo' => '62','nombre' => 'ARENAL','departamento' => '13'),
  array('codigo' => '63','nombre' => 'ARGELIA','departamento' => '5'),
  array('codigo' => '64','nombre' => 'ARGELIA','departamento' => '19'),
  array('codigo' => '65','nombre' => 'ARGELIA','departamento' => '76'),
  array('codigo' => '66','nombre' => 'ARIGUANI','departamento' => '47'),
  array('codigo' => '67','nombre' => 'ARJONA','departamento' => '13'),
  array('codigo' => '68','nombre' => 'ARMENIA','departamento' => '5'),
  array('codigo' => '69','nombre' => 'ARMENIA','departamento' => '63'),
  array('codigo' => '70','nombre' => 'ARMERO','departamento' => '73'),
  array('codigo' => '71','nombre' => 'ARROYOHONDO','departamento' => '13'),
  array('codigo' => '72','nombre' => 'ASTREA','departamento' => '20'),
  array('codigo' => '73','nombre' => 'ATACO','departamento' => '73'),
  array('codigo' => '74','nombre' => 'ATRATO','departamento' => '27'),
  array('codigo' => '75','nombre' => 'AYAPEL','departamento' => '23'),
  array('codigo' => '76','nombre' => 'BAGADO','departamento' => '27'),
  array('codigo' => '77','nombre' => 'BAHIA SOLANO','departamento' => '27'),
  array('codigo' => '78','nombre' => 'BAJO BAUDO','departamento' => '27'),
  array('codigo' => '79','nombre' => 'BALBOA','departamento' => '19'),
  array('codigo' => '80','nombre' => 'BALBOA','departamento' => '66'),
  array('codigo' => '81','nombre' => 'BARANOA','departamento' => '8'),
  array('codigo' => '82','nombre' => 'BARAYA','departamento' => '41'),
  array('codigo' => '83','nombre' => 'BARBACOAS','departamento' => '52'),
  array('codigo' => '84','nombre' => 'BARBOSA','departamento' => '5'),
  array('codigo' => '85','nombre' => 'BARBOSA','departamento' => '68'),
  array('codigo' => '86','nombre' => 'BARICHARA','departamento' => '68'),
  array('codigo' => '87','nombre' => 'BARRANCA DE UPIA','departamento' => '50'),
  array('codigo' => '88','nombre' => 'BARRANCABERMEJA','departamento' => '68'),
  array('codigo' => '89','nombre' => 'BARRANCAS','departamento' => '44'),
  array('codigo' => '90','nombre' => 'BARRANCO DE LOBA','departamento' => '13'),
  array('codigo' => '91','nombre' => 'BARRANCO MINAS','departamento' => '94'),
  array('codigo' => '92','nombre' => 'BARRANQUILLA','departamento' => '8'),
  array('codigo' => '93','nombre' => 'BECERRIL','departamento' => '20'),
  array('codigo' => '94','nombre' => 'BELALCAZAR','departamento' => '17'),
  array('codigo' => '95','nombre' => 'BELEN','departamento' => '15'),
  array('codigo' => '96','nombre' => 'BELEN','departamento' => '52'),
  array('codigo' => '97','nombre' => 'BELEN DE LOS ANDAQUIES','departamento' => '18'),
  array('codigo' => '98','nombre' => 'BELEN DE UMBRIA','departamento' => '66'),
  array('codigo' => '99','nombre' => 'BELLO','departamento' => '5'),
  array('codigo' => '100','nombre' => 'BELMIRA','departamento' => '5'),
  array('codigo' => '101','nombre' => 'BELTRAN','departamento' => '25'),
  array('codigo' => '102','nombre' => 'BERBEO','departamento' => '15'),
  array('codigo' => '103','nombre' => 'BETANIA','departamento' => '5'),
  array('codigo' => '104','nombre' => 'BETEITIVA','departamento' => '15'),
  array('codigo' => '105','nombre' => 'BETULIA','departamento' => '5'),
  array('codigo' => '106','nombre' => 'BETULIA','departamento' => '68'),
  array('codigo' => '107','nombre' => 'BITUIMA','departamento' => '25'),
  array('codigo' => '108','nombre' => 'BOAVITA','departamento' => '15'),
  array('codigo' => '109','nombre' => 'BOCHALEMA','departamento' => '54'),
  array('codigo' => '110','nombre' => 'BOGOTA, D.C.','departamento' => '11'),
  array('codigo' => '111','nombre' => 'BOJACA','departamento' => '25'),
  array('codigo' => '112','nombre' => 'BOJAYA','departamento' => '27'),
  array('codigo' => '113','nombre' => 'BOLIVAR','departamento' => '19'),
  array('codigo' => '114','nombre' => 'BOLIVAR','departamento' => '68'),
  array('codigo' => '115','nombre' => 'BOLIVAR','departamento' => '76'),
  array('codigo' => '116','nombre' => 'BOSCONIA','departamento' => '20'),
  array('codigo' => '117','nombre' => 'BOYACA','departamento' => '15'),
  array('codigo' => '118','nombre' => 'BRICEÑO','departamento' => '5'),
  array('codigo' => '119','nombre' => 'BRICEÑO','departamento' => '15'),
  array('codigo' => '120','nombre' => 'BUCARAMANGA','departamento' => '68'),
  array('codigo' => '121','nombre' => 'BUCARASICA','departamento' => '54'),
  array('codigo' => '122','nombre' => 'BUENAVENTURA','departamento' => '76'),
  array('codigo' => '123','nombre' => 'BUENAVISTA','departamento' => '15'),
  array('codigo' => '124','nombre' => 'BUENAVISTA','departamento' => '23'),
  array('codigo' => '125','nombre' => 'BUENAVISTA','departamento' => '63'),
  array('codigo' => '126','nombre' => 'BUENAVISTA','departamento' => '70'),
  array('codigo' => '127','nombre' => 'BUENOS AIRES','departamento' => '19'),
  array('codigo' => '128','nombre' => 'BUESACO','departamento' => '52'),
  array('codigo' => '129','nombre' => 'BUGA','departamento' => '76'),
  array('codigo' => '130','nombre' => 'BURITICA','departamento' => '5'),
  array('codigo' => '131','nombre' => 'BUSBANZA','departamento' => '15'),
  array('codigo' => '132','nombre' => 'CAÑASGORDAS','departamento' => '5'),
  array('codigo' => '133','nombre' => 'CABRERA','departamento' => '25'),
  array('codigo' => '134','nombre' => 'CABRERA','departamento' => '68'),
  array('codigo' => '135','nombre' => 'CABUYARO','departamento' => '50'),
  array('codigo' => '136','nombre' => 'CACAHUAL','departamento' => '94'),
  array('codigo' => '137','nombre' => 'CACERES','departamento' => '5'),
  array('codigo' => '138','nombre' => 'CACHIPAY','departamento' => '25'),
  array('codigo' => '139','nombre' => 'CACHIRA','departamento' => '54'),
  array('codigo' => '140','nombre' => 'CACOTA','departamento' => '54'),
  array('codigo' => '141','nombre' => 'CAICEDO','departamento' => '5'),
  array('codigo' => '142','nombre' => 'CAICEDONIA','departamento' => '76'),
  array('codigo' => '143','nombre' => 'CAIMITO','departamento' => '70'),
  array('codigo' => '144','nombre' => 'CAJAMARCA','departamento' => '73'),
  array('codigo' => '145','nombre' => 'CAJIBIO','departamento' => '19'),
  array('codigo' => '146','nombre' => 'CAJICA','departamento' => '25'),
  array('codigo' => '147','nombre' => 'CALAMAR','departamento' => '13'),
  array('codigo' => '148','nombre' => 'CALAMAR','departamento' => '95'),
  array('codigo' => '149','nombre' => 'CALARCA','departamento' => '63'),
  array('codigo' => '150','nombre' => 'CALDAS','departamento' => '5'),
  array('codigo' => '151','nombre' => 'CALDAS','departamento' => '15'),
  array('codigo' => '152','nombre' => 'CALDONO','departamento' => '19'),
  array('codigo' => '153','nombre' => 'CALI','departamento' => '76'),
  array('codigo' => '154','nombre' => 'CALIFORNIA','departamento' => '68'),
  array('codigo' => '155','nombre' => 'CALIMA','departamento' => '76'),
  array('codigo' => '156','nombre' => 'CALOTO','departamento' => '19'),
  array('codigo' => '157','nombre' => 'CAMPAMENTO','departamento' => '5'),
  array('codigo' => '158','nombre' => 'CAMPO DE LA CRUZ','departamento' => '8'),
  array('codigo' => '159','nombre' => 'CAMPOALEGRE','departamento' => '41'),
  array('codigo' => '160','nombre' => 'CAMPOHERMOSO','departamento' => '15'),
  array('codigo' => '161','nombre' => 'CANALETE','departamento' => '23'),
  array('codigo' => '162','nombre' => 'CANDELARIA','departamento' => '8'),
  array('codigo' => '163','nombre' => 'CANDELARIA','departamento' => '76'),
  array('codigo' => '164','nombre' => 'CANTAGALLO','departamento' => '13'),
  array('codigo' => '165','nombre' => 'CAPARRAPI','departamento' => '25'),
  array('codigo' => '166','nombre' => 'CAPITANEJO','departamento' => '68'),
  array('codigo' => '167','nombre' => 'CAQUEZA','departamento' => '25'),
  array('codigo' => '168','nombre' => 'CARACOLI','departamento' => '5'),
  array('codigo' => '169','nombre' => 'CARAMANTA','departamento' => '5'),
  array('codigo' => '170','nombre' => 'CARCASI','departamento' => '68'),
  array('codigo' => '171','nombre' => 'CAREPA','departamento' => '5'),
  array('codigo' => '172','nombre' => 'CARMEN DE APICALA','departamento' => '73'),
  array('codigo' => '173','nombre' => 'CARMEN DE CARUPA','departamento' => '25'),
  array('codigo' => '174','nombre' => 'CARMEN DEL DARIEN','departamento' => '27'),
  array('codigo' => '175','nombre' => 'CAROLINA','departamento' => '5'),
  array('codigo' => '176','nombre' => 'CARTAGENA','departamento' => '13'),
  array('codigo' => '177','nombre' => 'CARTAGENA DEL CHAIRA','departamento' => '18'),
  array('codigo' => '178','nombre' => 'CARTAGO','departamento' => '76'),
  array('codigo' => '179','nombre' => 'CARURU','departamento' => '97'),
  array('codigo' => '180','nombre' => 'CASABIANCA','departamento' => '73'),
  array('codigo' => '181','nombre' => 'CASTILLA LA NUEVA','departamento' => '50'),
  array('codigo' => '182','nombre' => 'CAUCASIA','departamento' => '5'),
  array('codigo' => '183','nombre' => 'CEPITA','departamento' => '68'),
  array('codigo' => '184','nombre' => 'CERETE','departamento' => '23'),
  array('codigo' => '185','nombre' => 'CERINZA','departamento' => '15'),
  array('codigo' => '186','nombre' => 'CERRITO','departamento' => '68'),
  array('codigo' => '187','nombre' => 'CERRO SAN ANTONIO','departamento' => '47'),
  array('codigo' => '188','nombre' => 'CERTEGUI','departamento' => '27'),
  array('codigo' => '189','nombre' => 'CHACHAGsI','departamento' => '52'),
  array('codigo' => '190','nombre' => 'CHAGUANI','departamento' => '25'),
  array('codigo' => '191','nombre' => 'CHALAN','departamento' => '70'),
  array('codigo' => '192','nombre' => 'CHAMEZA','departamento' => '85'),
  array('codigo' => '193','nombre' => 'CHAPARRAL','departamento' => '73'),
  array('codigo' => '194','nombre' => 'CHARALA','departamento' => '68'),
  array('codigo' => '195','nombre' => 'CHARTA','departamento' => '68'),
  array('codigo' => '196','nombre' => 'CHIA','departamento' => '25'),
  array('codigo' => '197','nombre' => 'CHIBOLO','departamento' => '47'),
  array('codigo' => '198','nombre' => 'CHIGORODO','departamento' => '5'),
  array('codigo' => '199','nombre' => 'CHIMA','departamento' => '23'),
  array('codigo' => '200','nombre' => 'CHIMA','departamento' => '68'),
  array('codigo' => '201','nombre' => 'CHIMICHAGUA','departamento' => '20'),
  array('codigo' => '202','nombre' => 'CHINACOTA','departamento' => '54'),
  array('codigo' => '203','nombre' => 'CHINAVITA','departamento' => '15'),
  array('codigo' => '204','nombre' => 'CHINCHINA','departamento' => '17'),
  array('codigo' => '205','nombre' => 'CHINU','departamento' => '23'),
  array('codigo' => '206','nombre' => 'CHIPAQUE','departamento' => '25'),
  array('codigo' => '207','nombre' => 'CHIPATA','departamento' => '68'),
  array('codigo' => '208','nombre' => 'CHIQUINQUIRA','departamento' => '15'),
  array('codigo' => '209','nombre' => 'CHIQUIZA','departamento' => '15'),
  array('codigo' => '210','nombre' => 'CHIRIGUANA','departamento' => '20'),
  array('codigo' => '211','nombre' => 'CHISCAS','departamento' => '15'),
  array('codigo' => '212','nombre' => 'CHITA','departamento' => '15'),
  array('codigo' => '213','nombre' => 'CHITAGA','departamento' => '54'),
  array('codigo' => '214','nombre' => 'CHITARAQUE','departamento' => '15'),
  array('codigo' => '215','nombre' => 'CHIVATA','departamento' => '15'),
  array('codigo' => '216','nombre' => 'CHIVOR','departamento' => '15'),
  array('codigo' => '217','nombre' => 'CHOACHI','departamento' => '25'),
  array('codigo' => '218','nombre' => 'CHOCONTA','departamento' => '25'),
  array('codigo' => '219','nombre' => 'CICUCO','departamento' => '13'),
  array('codigo' => '220','nombre' => 'CIENAGA','departamento' => '47'),
  array('codigo' => '221','nombre' => 'CIENAGA DE ORO','departamento' => '23'),
  array('codigo' => '222','nombre' => 'CIENEGA','departamento' => '15'),
  array('codigo' => '223','nombre' => 'CIMITARRA','departamento' => '68'),
  array('codigo' => '224','nombre' => 'CIRCASIA','departamento' => '63'),
  array('codigo' => '225','nombre' => 'CISNEROS','departamento' => '5'),
  array('codigo' => '226','nombre' => 'CIUDAD BOLIVAR','departamento' => '5'),
  array('codigo' => '227','nombre' => 'CLEMENCIA','departamento' => '13'),
  array('codigo' => '228','nombre' => 'COCORNA','departamento' => '5'),
  array('codigo' => '229','nombre' => 'COELLO','departamento' => '73'),
  array('codigo' => '230','nombre' => 'COGUA','departamento' => '25'),
  array('codigo' => '231','nombre' => 'COLOMBIA','departamento' => '41'),
  array('codigo' => '232','nombre' => 'COLON','departamento' => '52'),
  array('codigo' => '233','nombre' => 'COLON','departamento' => '86'),
  array('codigo' => '234','nombre' => 'COLOSO','departamento' => '70'),
  array('codigo' => '235','nombre' => 'COMBITA','departamento' => '15'),
  array('codigo' => '236','nombre' => 'CONCEPCION','departamento' => '5'),
  array('codigo' => '237','nombre' => 'CONCEPCION','departamento' => '68'),
  array('codigo' => '238','nombre' => 'CONCORDIA','departamento' => '5'),
  array('codigo' => '239','nombre' => 'CONCORDIA','departamento' => '47'),
  array('codigo' => '240','nombre' => 'CONDOTO','departamento' => '27'),
  array('codigo' => '241','nombre' => 'CONFINES','departamento' => '68'),
  array('codigo' => '242','nombre' => 'CONSACA','departamento' => '52'),
  array('codigo' => '243','nombre' => 'CONTADERO','departamento' => '52'),
  array('codigo' => '244','nombre' => 'CONTRATACION','departamento' => '68'),
  array('codigo' => '245','nombre' => 'CONVENCION','departamento' => '54'),
  array('codigo' => '246','nombre' => 'COPACABANA','departamento' => '5'),
  array('codigo' => '247','nombre' => 'COPER','departamento' => '15'),
  array('codigo' => '248','nombre' => 'CORDOBA','departamento' => '13'),
  array('codigo' => '249','nombre' => 'CORDOBA','departamento' => '52'),
  array('codigo' => '250','nombre' => 'CORDOBA','departamento' => '63'),
  array('codigo' => '251','nombre' => 'CORINTO','departamento' => '19'),
  array('codigo' => '252','nombre' => 'COROMORO','departamento' => '68'),
  array('codigo' => '253','nombre' => 'COROZAL','departamento' => '70'),
  array('codigo' => '254','nombre' => 'CORRALES','departamento' => '15'),
  array('codigo' => '255','nombre' => 'COTA','departamento' => '25'),
  array('codigo' => '256','nombre' => 'COTORRA','departamento' => '23'),
  array('codigo' => '257','nombre' => 'COVARACHIA','departamento' => '15'),
  array('codigo' => '258','nombre' => 'COVEÑAS','departamento' => '70'),
  array('codigo' => '259','nombre' => 'COYAIMA','departamento' => '73'),
  array('codigo' => '260','nombre' => 'CRAVO NORTE','departamento' => '81'),
  array('codigo' => '261','nombre' => 'CUASPUD','departamento' => '52'),
  array('codigo' => '262','nombre' => 'CUBARA','departamento' => '15'),
  array('codigo' => '263','nombre' => 'CUBARRAL','departamento' => '50'),
  array('codigo' => '264','nombre' => 'CUCAITA','departamento' => '15'),
  array('codigo' => '265','nombre' => 'CUCUNUBA','departamento' => '25'),
  array('codigo' => '266','nombre' => 'CUCUTA','departamento' => '54'),
  array('codigo' => '267','nombre' => 'CUCUTILLA','departamento' => '54'),
  array('codigo' => '268','nombre' => 'CUITIVA','departamento' => '15'),
  array('codigo' => '269','nombre' => 'CUMARAL','departamento' => '50'),
  array('codigo' => '270','nombre' => 'CUMARIBO','departamento' => '99'),
  array('codigo' => '271','nombre' => 'CUMBAL','departamento' => '52'),
  array('codigo' => '272','nombre' => 'CUMBITARA','departamento' => '52'),
  array('codigo' => '273','nombre' => 'CUNDAY','departamento' => '73'),
  array('codigo' => '274','nombre' => 'CURILLO','departamento' => '18'),
  array('codigo' => '275','nombre' => 'CURITI','departamento' => '68'),
  array('codigo' => '276','nombre' => 'CURUMANI','departamento' => '20'),
  array('codigo' => '277','nombre' => 'DABEIBA','departamento' => '5'),
  array('codigo' => '278','nombre' => 'DAGUA','departamento' => '76'),
  array('codigo' => '279','nombre' => 'DIBULLA','departamento' => '44'),
  array('codigo' => '280','nombre' => 'DISTRACCION','departamento' => '44'),
  array('codigo' => '281','nombre' => 'DOLORES','departamento' => '73'),
  array('codigo' => '282','nombre' => 'DON MATIAS','departamento' => '5'),
  array('codigo' => '283','nombre' => 'DOSQUEBRADAS','departamento' => '66'),
  array('codigo' => '284','nombre' => 'DUITAMA','departamento' => '15'),
  array('codigo' => '285','nombre' => 'DURANIA','departamento' => '54'),
  array('codigo' => '286','nombre' => 'EBEJICO','departamento' => '5'),
  array('codigo' => '287','nombre' => 'EL AGUILA','departamento' => '76'),
  array('codigo' => '288','nombre' => 'EL BAGRE','departamento' => '5'),
  array('codigo' => '289','nombre' => 'EL BANCO','departamento' => '47'),
  array('codigo' => '290','nombre' => 'EL CAIRO','departamento' => '76'),
  array('codigo' => '291','nombre' => 'EL CALVARIO','departamento' => '50'),
  array('codigo' => '292','nombre' => 'EL CANTON DEL SAN PABLO','departamento' => '27'),
  array('codigo' => '293','nombre' => 'EL CARMEN','departamento' => '54'),
  array('codigo' => '294','nombre' => 'EL CARMEN DE ATRATO','departamento' => '27'),
  array('codigo' => '295','nombre' => 'EL CARMEN DE BOLIVAR','departamento' => '13'),
  array('codigo' => '296','nombre' => 'EL CARMEN DE CHUCURI','departamento' => '68'),
  array('codigo' => '297','nombre' => 'EL CARMEN DE VIBORAL','departamento' => '5'),
  array('codigo' => '298','nombre' => 'EL CASTILLO','departamento' => '50'),
  array('codigo' => '299','nombre' => 'EL CERRITO','departamento' => '76'),
  array('codigo' => '300','nombre' => 'EL CHARCO','departamento' => '52'),
  array('codigo' => '301','nombre' => 'EL COCUY','departamento' => '15'),
  array('codigo' => '302','nombre' => 'EL COLEGIO','departamento' => '25'),
  array('codigo' => '303','nombre' => 'EL COPEY','departamento' => '20'),
  array('codigo' => '304','nombre' => 'EL DONCELLO','departamento' => '18'),
  array('codigo' => '305','nombre' => 'EL DORADO','departamento' => '50'),
  array('codigo' => '306','nombre' => 'EL DOVIO','departamento' => '76'),
  array('codigo' => '307','nombre' => 'EL ENCANTO','departamento' => '91'),
  array('codigo' => '308','nombre' => 'EL ESPINO','departamento' => '15'),
  array('codigo' => '309','nombre' => 'EL GUACAMAYO','departamento' => '68'),
  array('codigo' => '310','nombre' => 'EL GUAMO','departamento' => '13'),
  array('codigo' => '311','nombre' => 'EL LITORAL DEL SAN JUAN','departamento' => '27'),
  array('codigo' => '312','nombre' => 'EL MOLINO','departamento' => '44'),
  array('codigo' => '313','nombre' => 'EL PASO','departamento' => '20'),
  array('codigo' => '314','nombre' => 'EL PAUJIL','departamento' => '18'),
  array('codigo' => '315','nombre' => 'EL PEÑOL','departamento' => '52'),
  array('codigo' => '316','nombre' => 'EL PEÑON','departamento' => '13'),
  array('codigo' => '317','nombre' => 'EL PEÑON','departamento' => '25'),
  array('codigo' => '318','nombre' => 'EL PEÑON','departamento' => '68'),
  array('codigo' => '319','nombre' => 'EL PIÑON','departamento' => '47'),
  array('codigo' => '320','nombre' => 'EL PLAYON','departamento' => '68'),
  array('codigo' => '321','nombre' => 'EL RETEN','departamento' => '47'),
  array('codigo' => '322','nombre' => 'EL RETORNO','departamento' => '95'),
  array('codigo' => '323','nombre' => 'EL ROBLE','departamento' => '70'),
  array('codigo' => '324','nombre' => 'EL ROSAL','departamento' => '25'),
  array('codigo' => '325','nombre' => 'EL ROSARIO','departamento' => '52'),
  array('codigo' => '326','nombre' => 'EL SANTUARIO','departamento' => '5'),
  array('codigo' => '327','nombre' => 'EL TABLON DE GOMEZ','departamento' => '52'),
  array('codigo' => '328','nombre' => 'EL TAMBO','departamento' => '19'),
  array('codigo' => '329','nombre' => 'EL TAMBO','departamento' => '52'),
  array('codigo' => '330','nombre' => 'EL TARRA','departamento' => '54'),
  array('codigo' => '331','nombre' => 'EL ZULIA','departamento' => '54'),
  array('codigo' => '332','nombre' => 'ELIAS','departamento' => '41'),
  array('codigo' => '333','nombre' => 'ENCINO','departamento' => '68'),
  array('codigo' => '334','nombre' => 'ENCISO','departamento' => '68'),
  array('codigo' => '335','nombre' => 'ENTRERRIOS','departamento' => '5'),
  array('codigo' => '336','nombre' => 'ENVIGADO','departamento' => '5'),
  array('codigo' => '337','nombre' => 'ESPINAL','departamento' => '73'),
  array('codigo' => '338','nombre' => 'FACATATIVA','departamento' => '25'),
  array('codigo' => '339','nombre' => 'FALAN','departamento' => '73'),
  array('codigo' => '340','nombre' => 'FILADELFIA','departamento' => '17'),
  array('codigo' => '341','nombre' => 'FILANDIA','departamento' => '63'),
  array('codigo' => '342','nombre' => 'FIRAVITOBA','departamento' => '15'),
  array('codigo' => '343','nombre' => 'FLANDES','departamento' => '73'),
  array('codigo' => '344','nombre' => 'FLORENCIA','departamento' => '18'),
  array('codigo' => '345','nombre' => 'FLORENCIA','departamento' => '19'),
  array('codigo' => '346','nombre' => 'FLORESTA','departamento' => '15'),
  array('codigo' => '347','nombre' => 'FLORIAN','departamento' => '68'),
  array('codigo' => '348','nombre' => 'FLORIDA','departamento' => '76'),
  array('codigo' => '349','nombre' => 'FLORIDABLANCA','departamento' => '68'),
  array('codigo' => '350','nombre' => 'FOMEQUE','departamento' => '25'),
  array('codigo' => '351','nombre' => 'FONSECA','departamento' => '44'),
  array('codigo' => '352','nombre' => 'FORTUL','departamento' => '81'),
  array('codigo' => '353','nombre' => 'FOSCA','departamento' => '25'),
  array('codigo' => '354','nombre' => 'FRANCISCO PIZARRO','departamento' => '52'),
  array('codigo' => '355','nombre' => 'FREDONIA','departamento' => '5'),
  array('codigo' => '356','nombre' => 'FRESNO','departamento' => '73'),
  array('codigo' => '357','nombre' => 'FRONTINO','departamento' => '5'),
  array('codigo' => '358','nombre' => 'FUENTE DE ORO','departamento' => '50'),
  array('codigo' => '359','nombre' => 'FUNDACION','departamento' => '47'),
  array('codigo' => '360','nombre' => 'FUNES','departamento' => '52'),
  array('codigo' => '361','nombre' => 'FUNZA','departamento' => '25'),
  array('codigo' => '362','nombre' => 'FUQUENE','departamento' => '25'),
  array('codigo' => '363','nombre' => 'FUSAGASUGA','departamento' => '25'),
  array('codigo' => '364','nombre' => 'GACHALA','departamento' => '25'),
  array('codigo' => '365','nombre' => 'GACHANCIPA','departamento' => '25'),
  array('codigo' => '366','nombre' => 'GACHANTIVA','departamento' => '15'),
  array('codigo' => '367','nombre' => 'GACHETA','departamento' => '25'),
  array('codigo' => '368','nombre' => 'GALAN','departamento' => '68'),
  array('codigo' => '369','nombre' => 'GALAPA','departamento' => '8'),
  array('codigo' => '370','nombre' => 'GALERAS','departamento' => '70'),
  array('codigo' => '371','nombre' => 'GAMA','departamento' => '25'),
  array('codigo' => '372','nombre' => 'GAMARRA','departamento' => '20'),
  array('codigo' => '373','nombre' => 'GAMBITA','departamento' => '68'),
  array('codigo' => '374','nombre' => 'GAMEZA','departamento' => '15'),
  array('codigo' => '375','nombre' => 'GARAGOA','departamento' => '15'),
  array('codigo' => '376','nombre' => 'GARZON','departamento' => '41'),
  array('codigo' => '377','nombre' => 'GENOVA','departamento' => '63'),
  array('codigo' => '378','nombre' => 'GIGANTE','departamento' => '41'),
  array('codigo' => '379','nombre' => 'GINEBRA','departamento' => '76'),
  array('codigo' => '380','nombre' => 'GIRALDO','departamento' => '5'),
  array('codigo' => '381','nombre' => 'GIRARDOT','departamento' => '25'),
  array('codigo' => '382','nombre' => 'GIRARDOTA','departamento' => '5'),
  array('codigo' => '383','nombre' => 'GIRON','departamento' => '68'),
  array('codigo' => '384','nombre' => 'GOMEZ PLATA','departamento' => '5'),
  array('codigo' => '385','nombre' => 'GONZALEZ','departamento' => '20'),
  array('codigo' => '386','nombre' => 'GRAMALOTE','departamento' => '54'),
  array('codigo' => '387','nombre' => 'GRANADA','departamento' => '5'),
  array('codigo' => '388','nombre' => 'GRANADA','departamento' => '25'),
  array('codigo' => '389','nombre' => 'GRANADA','departamento' => '50'),
  array('codigo' => '390','nombre' => 'GSEPSA','departamento' => '68'),
  array('codigo' => '391','nombre' => 'GSICAN','departamento' => '15'),
  array('codigo' => '392','nombre' => 'GUACA','departamento' => '68'),
  array('codigo' => '393','nombre' => 'GUACAMAYAS','departamento' => '15'),
  array('codigo' => '394','nombre' => 'GUACARI','departamento' => '76'),
  array('codigo' => '395','nombre' => 'GUACHENE','departamento' => '19'),
  array('codigo' => '396','nombre' => 'GUACHETA','departamento' => '25'),
  array('codigo' => '397','nombre' => 'GUACHUCAL','departamento' => '52'),
  array('codigo' => '398','nombre' => 'GUADALAJARA DE BUGA','departamento' => '76'),
  array('codigo' => '399','nombre' => 'GUADALUPE','departamento' => '5'),
  array('codigo' => '400','nombre' => 'GUADALUPE','departamento' => '41'),
  array('codigo' => '401','nombre' => 'GUADALUPE','departamento' => '68'),
  array('codigo' => '402','nombre' => 'GUADUAS','departamento' => '25'),
  array('codigo' => '403','nombre' => 'GUAITARILLA','departamento' => '52'),
  array('codigo' => '404','nombre' => 'GUALMATAN','departamento' => '52'),
  array('codigo' => '405','nombre' => 'GUAMAL','departamento' => '47'),
  array('codigo' => '406','nombre' => 'GUAMAL','departamento' => '50'),
  array('codigo' => '407','nombre' => 'GUAMO','departamento' => '73'),
  array('codigo' => '408','nombre' => 'GUAPI','departamento' => '19'),
  array('codigo' => '409','nombre' => 'GUAPOTA','departamento' => '68'),
  array('codigo' => '410','nombre' => 'GUARANDA','departamento' => '70'),
  array('codigo' => '411','nombre' => 'GUARNE','departamento' => '5'),
  array('codigo' => '412','nombre' => 'GUASCA','departamento' => '25'),
  array('codigo' => '413','nombre' => 'GUATAPE','departamento' => '5'),
  array('codigo' => '414','nombre' => 'GUATAQUI','departamento' => '25'),
  array('codigo' => '415','nombre' => 'GUATAVITA','departamento' => '25'),
  array('codigo' => '416','nombre' => 'GUATEQUE','departamento' => '15'),
  array('codigo' => '417','nombre' => 'GUATICA','departamento' => '66'),
  array('codigo' => '418','nombre' => 'GUAVATA','departamento' => '68'),
  array('codigo' => '419','nombre' => 'GUAYABAL DE SIQUIMA','departamento' => '25'),
  array('codigo' => '420','nombre' => 'GUAYABETAL','departamento' => '25'),
  array('codigo' => '421','nombre' => 'GUAYATA','departamento' => '15'),
  array('codigo' => '422','nombre' => 'GUTIERREZ','departamento' => '25'),
  array('codigo' => '423','nombre' => 'HACARI','departamento' => '54'),
  array('codigo' => '424','nombre' => 'HATILLO DE LOBA','departamento' => '13'),
  array('codigo' => '425','nombre' => 'HATO','departamento' => '68'),
  array('codigo' => '426','nombre' => 'HATO COROZAL','departamento' => '85'),
  array('codigo' => '427','nombre' => 'HATONUEVO','departamento' => '44'),
  array('codigo' => '428','nombre' => 'HELICONIA','departamento' => '5'),
  array('codigo' => '429','nombre' => 'HERRAN','departamento' => '54'),
  array('codigo' => '430','nombre' => 'HERVEO','departamento' => '73'),
  array('codigo' => '431','nombre' => 'HISPANIA','departamento' => '5'),
  array('codigo' => '432','nombre' => 'HOBO','departamento' => '41'),
  array('codigo' => '433','nombre' => 'HONDA','departamento' => '73'),
  array('codigo' => '434','nombre' => 'IBAGUE','departamento' => '73'),
  array('codigo' => '435','nombre' => 'ICONONZO','departamento' => '73'),
  array('codigo' => '436','nombre' => 'ILES','departamento' => '52'),
  array('codigo' => '437','nombre' => 'IMUES','departamento' => '52'),
  array('codigo' => '438','nombre' => 'INIRIDA','departamento' => '94'),
  array('codigo' => '439','nombre' => 'INZA','departamento' => '19'),
  array('codigo' => '440','nombre' => 'IPIALES','departamento' => '52'),
  array('codigo' => '441','nombre' => 'IQUIRA','departamento' => '41'),
  array('codigo' => '442','nombre' => 'ISNOS','departamento' => '41'),
  array('codigo' => '443','nombre' => 'ISTMINA','departamento' => '27'),
  array('codigo' => '444','nombre' => 'ITAGUI','departamento' => '5'),
  array('codigo' => '445','nombre' => 'ITUANGO','departamento' => '5'),
  array('codigo' => '446','nombre' => 'IZA','departamento' => '15'),
  array('codigo' => '447','nombre' => 'JAMBALO','departamento' => '19'),
  array('codigo' => '448','nombre' => 'JAMUNDI','departamento' => '76'),
  array('codigo' => '449','nombre' => 'JARDIN','departamento' => '5'),
  array('codigo' => '450','nombre' => 'JENESANO','departamento' => '15'),
  array('codigo' => '451','nombre' => 'JERICO','departamento' => '5'),
  array('codigo' => '452','nombre' => 'JERICO','departamento' => '15'),
  array('codigo' => '453','nombre' => 'JERUSALEN','departamento' => '25'),
  array('codigo' => '454','nombre' => 'JESUS MARIA','departamento' => '68'),
  array('codigo' => '455','nombre' => 'JORDAN','departamento' => '68'),
  array('codigo' => '456','nombre' => 'JUAN DE ACOSTA','departamento' => '8'),
  array('codigo' => '457','nombre' => 'JUNIN','departamento' => '25'),
  array('codigo' => '458','nombre' => 'JURADO','departamento' => '27'),
  array('codigo' => '459','nombre' => 'LA APARTADA','departamento' => '23'),
  array('codigo' => '460','nombre' => 'LA ARGENTINA','departamento' => '41'),
  array('codigo' => '461','nombre' => 'LA BELLEZA','departamento' => '68'),
  array('codigo' => '462','nombre' => 'LA CALERA','departamento' => '25'),
  array('codigo' => '463','nombre' => 'LA CAPILLA','departamento' => '15'),
  array('codigo' => '464','nombre' => 'LA CEJA','departamento' => '5'),
  array('codigo' => '465','nombre' => 'LA CELIA','departamento' => '66'),
  array('codigo' => '466','nombre' => 'LA CHORRERA','departamento' => '91'),
  array('codigo' => '467','nombre' => 'LA CRUZ','departamento' => '52'),
  array('codigo' => '468','nombre' => 'LA CUMBRE','departamento' => '76'),
  array('codigo' => '469','nombre' => 'LA DORADA','departamento' => '17'),
  array('codigo' => '470','nombre' => 'LA ESPERANZA','departamento' => '54'),
  array('codigo' => '471','nombre' => 'LA ESTRELLA','departamento' => '5'),
  array('codigo' => '472','nombre' => 'LA FLORIDA','departamento' => '52'),
  array('codigo' => '473','nombre' => 'LA GLORIA','departamento' => '20'),
  array('codigo' => '474','nombre' => 'LA GUADALUPE','departamento' => '94'),
  array('codigo' => '475','nombre' => 'LA JAGUA DE IBIRICO','departamento' => '20'),
  array('codigo' => '476','nombre' => 'LA JAGUA DEL PILAR','departamento' => '44'),
  array('codigo' => '477','nombre' => 'LA LLANADA','departamento' => '52'),
  array('codigo' => '478','nombre' => 'LA MACARENA','departamento' => '50'),
  array('codigo' => '479','nombre' => 'LA MERCED','departamento' => '17'),
  array('codigo' => '480','nombre' => 'LA MESA','departamento' => '25'),
  array('codigo' => '481','nombre' => 'LA MONTAÑITA','departamento' => '18'),
  array('codigo' => '482','nombre' => 'LA PALMA','departamento' => '25'),
  array('codigo' => '483','nombre' => 'LA PAZ','departamento' => '20'),
  array('codigo' => '484','nombre' => 'LA PAZ','departamento' => '68'),
  array('codigo' => '485','nombre' => 'LA PEÑA','departamento' => '25'),
  array('codigo' => '486','nombre' => 'LA PEDRERA','departamento' => '91'),
  array('codigo' => '487','nombre' => 'LA PINTADA','departamento' => '5'),
  array('codigo' => '488','nombre' => 'LA PLATA','departamento' => '41'),
  array('codigo' => '489','nombre' => 'LA PLAYA','departamento' => '54'),
  array('codigo' => '490','nombre' => 'LA PRIMAVERA','departamento' => '99'),
  array('codigo' => '491','nombre' => 'LA SALINA','departamento' => '85'),
  array('codigo' => '492','nombre' => 'LA SIERRA','departamento' => '19'),
  array('codigo' => '493','nombre' => 'LA TEBAIDA','departamento' => '63'),
  array('codigo' => '494','nombre' => 'LA TOLA','departamento' => '52'),
  array('codigo' => '495','nombre' => 'LA UNION','departamento' => '5'),
  array('codigo' => '496','nombre' => 'LA UNION','departamento' => '52'),
  array('codigo' => '497','nombre' => 'LA UNION','departamento' => '70'),
  array('codigo' => '498','nombre' => 'LA UNION','departamento' => '76'),
  array('codigo' => '499','nombre' => 'LA UVITA','departamento' => '15'),
  array('codigo' => '500','nombre' => 'LA VEGA','departamento' => '19'),
  array('codigo' => '501','nombre' => 'LA VEGA','departamento' => '25'),
  array('codigo' => '502','nombre' => 'LA VICTORIA','departamento' => '15'),
  array('codigo' => '503','nombre' => 'LA VICTORIA','departamento' => '76'),
  array('codigo' => '504','nombre' => 'LA VICTORIA','departamento' => '91'),
  array('codigo' => '505','nombre' => 'LA VIRGINIA','departamento' => '66'),
  array('codigo' => '506','nombre' => 'LABATECA','departamento' => '54'),
  array('codigo' => '507','nombre' => 'LABRANZAGRANDE','departamento' => '15'),
  array('codigo' => '508','nombre' => 'LANDAZURI','departamento' => '68'),
  array('codigo' => '509','nombre' => 'LEBRIJA','departamento' => '68'),
  array('codigo' => '510','nombre' => 'LEGUIZAMO','departamento' => '86'),
  array('codigo' => '511','nombre' => 'LEIVA','departamento' => '52'),
  array('codigo' => '512','nombre' => 'LEJANIAS','departamento' => '50'),
  array('codigo' => '513','nombre' => 'LENGUAZAQUE','departamento' => '25'),
  array('codigo' => '514','nombre' => 'LERIDA','departamento' => '73'),
  array('codigo' => '515','nombre' => 'LETICIA','departamento' => '91'),
  array('codigo' => '516','nombre' => 'LIBANO','departamento' => '73'),
  array('codigo' => '517','nombre' => 'LIBORINA','departamento' => '5'),
  array('codigo' => '518','nombre' => 'LINARES','departamento' => '52'),
  array('codigo' => '519','nombre' => 'LLORO','departamento' => '27'),
  array('codigo' => '520','nombre' => 'LOPEZ','departamento' => '19'),
  array('codigo' => '521','nombre' => 'LORICA','departamento' => '23'),
  array('codigo' => '522','nombre' => 'LOS ANDES','departamento' => '52'),
  array('codigo' => '523','nombre' => 'LOS CORDOBAS','departamento' => '23'),
  array('codigo' => '524','nombre' => 'LOS PALMITOS','departamento' => '70'),
  array('codigo' => '525','nombre' => 'LOS PATIOS','departamento' => '54'),
  array('codigo' => '526','nombre' => 'LOS SANTOS','departamento' => '68'),
  array('codigo' => '527','nombre' => 'LOURDES','departamento' => '54'),
  array('codigo' => '528','nombre' => 'LURUACO','departamento' => '8'),
  array('codigo' => '529','nombre' => 'MACANAL','departamento' => '15'),
  array('codigo' => '530','nombre' => 'MACARAVITA','departamento' => '68'),
  array('codigo' => '531','nombre' => 'MACEO','departamento' => '5'),
  array('codigo' => '532','nombre' => 'MACHETA','departamento' => '25'),
  array('codigo' => '533','nombre' => 'MADRID','departamento' => '25'),
  array('codigo' => '534','nombre' => 'MAGANGUE','departamento' => '13'),
  array('codigo' => '535','nombre' => 'MAGsI','departamento' => '52'),
  array('codigo' => '536','nombre' => 'MAHATES','departamento' => '13'),
  array('codigo' => '537','nombre' => 'MAICAO','departamento' => '44'),
  array('codigo' => '538','nombre' => 'MAJAGUAL','departamento' => '70'),
  array('codigo' => '539','nombre' => 'MALAGA','departamento' => '68'),
  array('codigo' => '540','nombre' => 'MALAMBO','departamento' => '8'),
  array('codigo' => '541','nombre' => 'MALLAMA','departamento' => '52'),
  array('codigo' => '542','nombre' => 'MANATI','departamento' => '8'),
  array('codigo' => '543','nombre' => 'MANAURE','departamento' => '20'),
  array('codigo' => '544','nombre' => 'MANAURE','departamento' => '44'),
  array('codigo' => '545','nombre' => 'MANI','departamento' => '85'),
  array('codigo' => '546','nombre' => 'MANIZALES','departamento' => '17'),
  array('codigo' => '547','nombre' => 'MANTA','departamento' => '25'),
  array('codigo' => '548','nombre' => 'MANZANARES','departamento' => '17'),
  array('codigo' => '549','nombre' => 'MAPIRIPAN','departamento' => '50'),
  array('codigo' => '550','nombre' => 'MAPIRIPANA','departamento' => '94'),
  array('codigo' => '551','nombre' => 'MARGARITA','departamento' => '13'),
  array('codigo' => '552','nombre' => 'MARIA LA BAJA','departamento' => '13'),
  array('codigo' => '553','nombre' => 'MARINILLA','departamento' => '5'),
  array('codigo' => '554','nombre' => 'MARIPI','departamento' => '15'),
  array('codigo' => '555','nombre' => 'MARIQUITA','departamento' => '73'),
  array('codigo' => '556','nombre' => 'MARMATO','departamento' => '17'),
  array('codigo' => '557','nombre' => 'MARQUETALIA','departamento' => '17'),
  array('codigo' => '558','nombre' => 'MARSELLA','departamento' => '66'),
  array('codigo' => '559','nombre' => 'MARULANDA','departamento' => '17'),
  array('codigo' => '560','nombre' => 'MATANZA','departamento' => '68'),
  array('codigo' => '561','nombre' => 'MEDELLIN','departamento' => '5'),
  array('codigo' => '562','nombre' => 'MEDINA','departamento' => '25'),
  array('codigo' => '563','nombre' => 'MEDIO ATRATO','departamento' => '27'),
  array('codigo' => '564','nombre' => 'MEDIO BAUDO','departamento' => '27'),
  array('codigo' => '565','nombre' => 'MEDIO SAN JUAN','departamento' => '27'),
  array('codigo' => '566','nombre' => 'MELGAR','departamento' => '73'),
  array('codigo' => '567','nombre' => 'MERCADERES','departamento' => '19'),
  array('codigo' => '568','nombre' => 'MESETAS','departamento' => '50'),
  array('codigo' => '569','nombre' => 'MILAN','departamento' => '18'),
  array('codigo' => '570','nombre' => 'MIRAFLORES','departamento' => '15'),
  array('codigo' => '571','nombre' => 'MIRAFLORES','departamento' => '95'),
  array('codigo' => '572','nombre' => 'MIRANDA','departamento' => '19'),
  array('codigo' => '573','nombre' => 'MIRITI Ñ PARANA','departamento' => '91'),
  array('codigo' => '574','nombre' => 'MISTRATO','departamento' => '66'),
  array('codigo' => '575','nombre' => 'MITU','departamento' => '97'),
  array('codigo' => '576','nombre' => 'MOCOA','departamento' => '86'),
  array('codigo' => '577','nombre' => 'MOGOTES','departamento' => '68'),
  array('codigo' => '578','nombre' => 'MOÑITOS','departamento' => '23'),
  array('codigo' => '579','nombre' => 'MOLAGAVITA','departamento' => '68'),
  array('codigo' => '580','nombre' => 'MOMIL','departamento' => '23'),
  array('codigo' => '581','nombre' => 'MOMPOS','departamento' => '13'),
  array('codigo' => '582','nombre' => 'MONGUA','departamento' => '15'),
  array('codigo' => '583','nombre' => 'MONGUI','departamento' => '15'),
  array('codigo' => '584','nombre' => 'MONIQUIRA','departamento' => '15'),
  array('codigo' => '585','nombre' => 'MONTEBELLO','departamento' => '5'),
  array('codigo' => '586','nombre' => 'MONTECRISTO','departamento' => '13'),
  array('codigo' => '587','nombre' => 'MONTELIBANO','departamento' => '23'),
  array('codigo' => '588','nombre' => 'MONTENEGRO','departamento' => '63'),
  array('codigo' => '589','nombre' => 'MONTERIA','departamento' => '23'),
  array('codigo' => '590','nombre' => 'MONTERREY','departamento' => '85'),
  array('codigo' => '591','nombre' => 'MORALES','departamento' => '13'),
  array('codigo' => '592','nombre' => 'MORALES','departamento' => '19'),
  array('codigo' => '593','nombre' => 'MORELIA','departamento' => '18'),
  array('codigo' => '594','nombre' => 'MORICHAL','departamento' => '94'),
  array('codigo' => '595','nombre' => 'MORROA','departamento' => '70'),
  array('codigo' => '596','nombre' => 'MOSQUERA','departamento' => '25'),
  array('codigo' => '597','nombre' => 'MOSQUERA','departamento' => '52'),
  array('codigo' => '598','nombre' => 'MOTAVITA','departamento' => '15'),
  array('codigo' => '599','nombre' => 'MURILLO','departamento' => '73'),
  array('codigo' => '600','nombre' => 'MURINDO','departamento' => '5'),
  array('codigo' => '601','nombre' => 'MUTATA','departamento' => '5'),
  array('codigo' => '602','nombre' => 'MUTISCUA','departamento' => '54'),
  array('codigo' => '603','nombre' => 'MUZO','departamento' => '15'),
  array('codigo' => '604','nombre' => 'NARIÑO','departamento' => '5'),
  array('codigo' => '605','nombre' => 'NARIÑO','departamento' => '25'),
  array('codigo' => '606','nombre' => 'NARIÑO','departamento' => '52'),
  array('codigo' => '607','nombre' => 'NATAGA','departamento' => '41'),
  array('codigo' => '608','nombre' => 'NATAGAIMA','departamento' => '73'),
  array('codigo' => '609','nombre' => 'NECHI','departamento' => '5'),
  array('codigo' => '610','nombre' => 'NECOCLI','departamento' => '5'),
  array('codigo' => '611','nombre' => 'NEIRA','departamento' => '17'),
  array('codigo' => '612','nombre' => 'NEIVA','departamento' => '41'),
  array('codigo' => '613','nombre' => 'NEMOCON','departamento' => '25'),
  array('codigo' => '614','nombre' => 'NILO','departamento' => '25'),
  array('codigo' => '615','nombre' => 'NIMAIMA','departamento' => '25'),
  array('codigo' => '616','nombre' => 'NOBSA','departamento' => '15'),
  array('codigo' => '617','nombre' => 'NOCAIMA','departamento' => '25'),
  array('codigo' => '618','nombre' => 'NORCASIA','departamento' => '17'),
  array('codigo' => '619','nombre' => 'NOROSI','departamento' => '13'),
  array('codigo' => '620','nombre' => 'NOVITA','departamento' => '27'),
  array('codigo' => '621','nombre' => 'NUEVA GRANADA','departamento' => '47'),
  array('codigo' => '622','nombre' => 'NUEVO COLON','departamento' => '15'),
  array('codigo' => '623','nombre' => 'NUNCHIA','departamento' => '85'),
  array('codigo' => '624','nombre' => 'NUQUI','departamento' => '27'),
  array('codigo' => '625','nombre' => 'OBANDO','departamento' => '76'),
  array('codigo' => '626','nombre' => 'OCAÑA','departamento' => '54'),
  array('codigo' => '627','nombre' => 'OCAMONTE','departamento' => '68'),
  array('codigo' => '628','nombre' => 'OIBA','departamento' => '68'),
  array('codigo' => '629','nombre' => 'OICATA','departamento' => '15'),
  array('codigo' => '630','nombre' => 'OLAYA','departamento' => '5'),
  array('codigo' => '631','nombre' => 'OLAYA HERRERA','departamento' => '52'),
  array('codigo' => '632','nombre' => 'ONZAGA','departamento' => '68'),
  array('codigo' => '633','nombre' => 'OPORAPA','departamento' => '41'),
  array('codigo' => '634','nombre' => 'ORITO','departamento' => '86'),
  array('codigo' => '635','nombre' => 'OROCUE','departamento' => '85'),
  array('codigo' => '636','nombre' => 'ORTEGA','departamento' => '73'),
  array('codigo' => '637','nombre' => 'OSPINA','departamento' => '52'),
  array('codigo' => '638','nombre' => 'OTANCHE','departamento' => '15'),
  array('codigo' => '639','nombre' => 'OVEJAS','departamento' => '70'),
  array('codigo' => '640','nombre' => 'PACHAVITA','departamento' => '15'),
  array('codigo' => '641','nombre' => 'PACHO','departamento' => '25'),
  array('codigo' => '642','nombre' => 'PACOA','departamento' => '97'),
  array('codigo' => '643','nombre' => 'PACORA','departamento' => '17'),
  array('codigo' => '644','nombre' => 'PADILLA','departamento' => '19'),
  array('codigo' => '645','nombre' => 'PAEZ','departamento' => '15'),
  array('codigo' => '646','nombre' => 'PAEZ','departamento' => '19'),
  array('codigo' => '647','nombre' => 'PAICOL','departamento' => '41'),
  array('codigo' => '648','nombre' => 'PAILITAS','departamento' => '20'),
  array('codigo' => '649','nombre' => 'PAIME','departamento' => '25'),
  array('codigo' => '650','nombre' => 'PAIPA','departamento' => '15'),
  array('codigo' => '651','nombre' => 'PAJARITO','departamento' => '15'),
  array('codigo' => '652','nombre' => 'PALERMO','departamento' => '41'),
  array('codigo' => '653','nombre' => 'PALESTINA','departamento' => '17'),
  array('codigo' => '654','nombre' => 'PALESTINA','departamento' => '41'),
  array('codigo' => '655','nombre' => 'PALMAR','departamento' => '68'),
  array('codigo' => '656','nombre' => 'PALMAR DE VARELA','departamento' => '8'),
  array('codigo' => '657','nombre' => 'PALMAS DEL SOCORRO','departamento' => '68'),
  array('codigo' => '658','nombre' => 'PALMIRA','departamento' => '76'),
  array('codigo' => '659','nombre' => 'PALMITO','departamento' => '70'),
  array('codigo' => '660','nombre' => 'PALOCABILDO','departamento' => '73'),
  array('codigo' => '661','nombre' => 'PAMPLONA','departamento' => '54'),
  array('codigo' => '662','nombre' => 'PAMPLONITA','departamento' => '54'),
  array('codigo' => '663','nombre' => 'PANA PANA','departamento' => '94'),
  array('codigo' => '664','nombre' => 'PANDI','departamento' => '25'),
  array('codigo' => '665','nombre' => 'PANQUEBA','departamento' => '15'),
  array('codigo' => '666','nombre' => 'PAPUNAUA','departamento' => '97'),
  array('codigo' => '667','nombre' => 'PARAMO','departamento' => '68'),
  array('codigo' => '668','nombre' => 'PARATEBUENO','departamento' => '25'),
  array('codigo' => '669','nombre' => 'PASCA','departamento' => '25'),
  array('codigo' => '670','nombre' => 'PASTO','departamento' => '52'),
  array('codigo' => '671','nombre' => 'PATIA','departamento' => '19'),
  array('codigo' => '672','nombre' => 'PAUNA','departamento' => '15'),
  array('codigo' => '673','nombre' => 'PAYA','departamento' => '15'),
  array('codigo' => '674','nombre' => 'PAZ DE ARIPORO','departamento' => '85'),
  array('codigo' => '675','nombre' => 'PAZ DE RIO','departamento' => '15'),
  array('codigo' => '676','nombre' => 'PEDOL','departamento' => '5'),
  array('codigo' => '677','nombre' => 'PEDRAZA','departamento' => '47'),
  array('codigo' => '678','nombre' => 'PELAYA','departamento' => '20'),
  array('codigo' => '679','nombre' => 'PENSILVANIA','departamento' => '17'),
  array('codigo' => '680','nombre' => 'PEQUE','departamento' => '5'),
  array('codigo' => '681','nombre' => 'PEREIRA','departamento' => '66'),
  array('codigo' => '682','nombre' => 'PESCA','departamento' => '15'),
  array('codigo' => '683','nombre' => 'PIAMONTE','departamento' => '19'),
  array('codigo' => '684','nombre' => 'PIEDECUESTA','departamento' => '68'),
  array('codigo' => '685','nombre' => 'PIEDRAS','departamento' => '73'),
  array('codigo' => '686','nombre' => 'PIENDAMO','departamento' => '19'),
  array('codigo' => '687','nombre' => 'PIJAO','departamento' => '63'),
  array('codigo' => '688','nombre' => 'PIJIÑO DEL CARMEN','departamento' => '47'),
  array('codigo' => '689','nombre' => 'PINCHOTE','departamento' => '68'),
  array('codigo' => '690','nombre' => 'PINILLOS','departamento' => '13'),
  array('codigo' => '691','nombre' => 'PIOJO','departamento' => '8'),
  array('codigo' => '692','nombre' => 'PISBA','departamento' => '15'),
  array('codigo' => '693','nombre' => 'PITAL','departamento' => '41'),
  array('codigo' => '694','nombre' => 'PITALITO','departamento' => '41'),
  array('codigo' => '695','nombre' => 'PIVIJAY','departamento' => '47'),
  array('codigo' => '696','nombre' => 'PLANADAS','departamento' => '73'),
  array('codigo' => '697','nombre' => 'PLANETA RICA','departamento' => '23'),
  array('codigo' => '698','nombre' => 'PLATO','departamento' => '47'),
  array('codigo' => '699','nombre' => 'POLICARPA','departamento' => '52'),
  array('codigo' => '700','nombre' => 'POLONUEVO','departamento' => '8'),
  array('codigo' => '701','nombre' => 'PONEDERA','departamento' => '8'),
  array('codigo' => '702','nombre' => 'POPAYAN','departamento' => '19'),
  array('codigo' => '703','nombre' => 'PORE','departamento' => '85'),
  array('codigo' => '704','nombre' => 'POTOSI','departamento' => '52'),
  array('codigo' => '705','nombre' => 'PRADERA','departamento' => '76'),
  array('codigo' => '706','nombre' => 'PRADO','departamento' => '73'),
  array('codigo' => '707','nombre' => 'PROVIDENCIA','departamento' => '52'),
  array('codigo' => '708','nombre' => 'PROVIDENCIA','departamento' => '88'),
  array('codigo' => '709','nombre' => 'PUEBLO BELLO','departamento' => '20'),
  array('codigo' => '710','nombre' => 'PUEBLO NUEVO','departamento' => '23'),
  array('codigo' => '711','nombre' => 'PUEBLO RICO','departamento' => '66'),
  array('codigo' => '712','nombre' => 'PUEBLORRICO','departamento' => '5'),
  array('codigo' => '713','nombre' => 'PUEBLOVIEJO','departamento' => '47'),
  array('codigo' => '714','nombre' => 'PUENTE NACIONAL','departamento' => '68'),
  array('codigo' => '715','nombre' => 'PUERRES','departamento' => '52'),
  array('codigo' => '716','nombre' => 'PUERTO ALEGRIA','departamento' => '91'),
  array('codigo' => '717','nombre' => 'PUERTO ARICA','departamento' => '91'),
  array('codigo' => '718','nombre' => 'PUERTO ASIS','departamento' => '86'),
  array('codigo' => '719','nombre' => 'PUERTO BERRIO','departamento' => '5'),
  array('codigo' => '720','nombre' => 'PUERTO BOYACA','departamento' => '15'),
  array('codigo' => '721','nombre' => 'PUERTO CAICEDO','departamento' => '86'),
  array('codigo' => '722','nombre' => 'PUERTO CARREÑO','departamento' => '99'),
  array('codigo' => '723','nombre' => 'PUERTO COLOMBIA','departamento' => '8'),
  array('codigo' => '724','nombre' => 'PUERTO COLOMBIA','departamento' => '94'),
  array('codigo' => '725','nombre' => 'PUERTO CONCORDIA','departamento' => '50'),
  array('codigo' => '726','nombre' => 'PUERTO ESCONDIDO','departamento' => '23'),
  array('codigo' => '727','nombre' => 'PUERTO GAITAN','departamento' => '50'),
  array('codigo' => '728','nombre' => 'PUERTO GUZMAN','departamento' => '86'),
  array('codigo' => '729','nombre' => 'PUERTO LIBERTADOR','departamento' => '23'),
  array('codigo' => '730','nombre' => 'PUERTO LLERAS','departamento' => '50'),
  array('codigo' => '731','nombre' => 'PUERTO LOPEZ','departamento' => '50'),
  array('codigo' => '732','nombre' => 'PUERTO NARE','departamento' => '5'),
  array('codigo' => '733','nombre' => 'PUERTO NARIÑO','departamento' => '91'),
  array('codigo' => '734','nombre' => 'PUERTO PARRA','departamento' => '68'),
  array('codigo' => '735','nombre' => 'PUERTO RICO','departamento' => '18'),
  array('codigo' => '736','nombre' => 'PUERTO RICO','departamento' => '50'),
  array('codigo' => '737','nombre' => 'PUERTO RONDON','departamento' => '81'),
  array('codigo' => '738','nombre' => 'PUERTO SALGAR','departamento' => '25'),
  array('codigo' => '739','nombre' => 'PUERTO SANTANDER','departamento' => '54'),
  array('codigo' => '740','nombre' => 'PUERTO SANTANDER','departamento' => '91'),
  array('codigo' => '741','nombre' => 'PUERTO TEJADA','departamento' => '19'),
  array('codigo' => '742','nombre' => 'PUERTO TRIUNFO','departamento' => '5'),
  array('codigo' => '743','nombre' => 'PUERTO WILCHES','departamento' => '68'),
  array('codigo' => '744','nombre' => 'PULI','departamento' => '25'),
  array('codigo' => '745','nombre' => 'PUPIALES','departamento' => '52'),
  array('codigo' => '746','nombre' => 'PURACE','departamento' => '19'),
  array('codigo' => '747','nombre' => 'PURIFICACION','departamento' => '73'),
  array('codigo' => '748','nombre' => 'PURISIMA','departamento' => '23'),
  array('codigo' => '749','nombre' => 'QUEBRADANEGRA','departamento' => '25'),
  array('codigo' => '750','nombre' => 'QUETAME','departamento' => '25'),
  array('codigo' => '751','nombre' => 'QUIBDO','departamento' => '27'),
  array('codigo' => '752','nombre' => 'QUIMBAYA','departamento' => '63'),
  array('codigo' => '753','nombre' => 'QUINCHIA','departamento' => '66'),
  array('codigo' => '754','nombre' => 'QUIPAMA','departamento' => '15'),
  array('codigo' => '755','nombre' => 'QUIPILE','departamento' => '25'),
  array('codigo' => '756','nombre' => 'RAGONVALIA','departamento' => '54'),
  array('codigo' => '757','nombre' => 'RAMIRIQUI','departamento' => '15'),
  array('codigo' => '758','nombre' => 'RAQUIRA','departamento' => '15'),
  array('codigo' => '759','nombre' => 'RECETOR','departamento' => '85'),
  array('codigo' => '760','nombre' => 'REGIDOR','departamento' => '13'),
  array('codigo' => '761','nombre' => 'REMEDIOS','departamento' => '5'),
  array('codigo' => '762','nombre' => 'REMOLINO','departamento' => '47'),
  array('codigo' => '763','nombre' => 'REPELON','departamento' => '8'),
  array('codigo' => '764','nombre' => 'RESTREPO','departamento' => '50'),
  array('codigo' => '765','nombre' => 'RESTREPO','departamento' => '76'),
  array('codigo' => '766','nombre' => 'RETIRO','departamento' => '5'),
  array('codigo' => '767','nombre' => 'RICAURTE','departamento' => '25'),
  array('codigo' => '768','nombre' => 'RICAURTE','departamento' => '52'),
  array('codigo' => '769','nombre' => 'RIO DE ORO','departamento' => '20'),
  array('codigo' => '770','nombre' => 'RIO IRO','departamento' => '27'),
  array('codigo' => '771','nombre' => 'RIO QUITO','departamento' => '27'),
  array('codigo' => '772','nombre' => 'RIO VIEJO','departamento' => '13'),
  array('codigo' => '773','nombre' => 'RIOBLANCO','departamento' => '73'),
  array('codigo' => '774','nombre' => 'RIOFRIO','departamento' => '76'),
  array('codigo' => '775','nombre' => 'RIOHACHA','departamento' => '44'),
  array('codigo' => '776','nombre' => 'RIONEGRO','departamento' => '5'),
  array('codigo' => '777','nombre' => 'RIONEGRO','departamento' => '68'),
  array('codigo' => '778','nombre' => 'RIOSUCIO','departamento' => '17'),
  array('codigo' => '779','nombre' => 'RIOSUCIO','departamento' => '27'),
  array('codigo' => '780','nombre' => 'RISARALDA','departamento' => '17'),
  array('codigo' => '781','nombre' => 'RIVERA','departamento' => '41'),
  array('codigo' => '782','nombre' => 'ROBERTO PAYAN','departamento' => '52'),
  array('codigo' => '783','nombre' => 'ROLDANILLO','departamento' => '76'),
  array('codigo' => '784','nombre' => 'RONCESVALLES','departamento' => '73'),
  array('codigo' => '785','nombre' => 'RONDON','departamento' => '15'),
  array('codigo' => '786','nombre' => 'ROSAS','departamento' => '19'),
  array('codigo' => '787','nombre' => 'ROVIRA','departamento' => '73'),
  array('codigo' => '788','nombre' => 'SABANA DE TORRES','departamento' => '68'),
  array('codigo' => '789','nombre' => 'SABANAGRANDE','departamento' => '8'),
  array('codigo' => '790','nombre' => 'SABANALARGA','departamento' => '5'),
  array('codigo' => '791','nombre' => 'SABANALARGA','departamento' => '8'),
  array('codigo' => '792','nombre' => 'SABANALARGA','departamento' => '85'),
  array('codigo' => '793','nombre' => 'SABANAS DE SAN ANGEL','departamento' => '47'),
  array('codigo' => '794','nombre' => 'SABANETA','departamento' => '5'),
  array('codigo' => '795','nombre' => 'SABOYA','departamento' => '15'),
  array('codigo' => '796','nombre' => 'SACAMA','departamento' => '85'),
  array('codigo' => '797','nombre' => 'SACHICA','departamento' => '15'),
  array('codigo' => '798','nombre' => 'SAHAGUN','departamento' => '23'),
  array('codigo' => '799','nombre' => 'SALADOBLANCO','departamento' => '41'),
  array('codigo' => '800','nombre' => 'SALAMINA','departamento' => '17'),
  array('codigo' => '801','nombre' => 'SALAMINA','departamento' => '47'),
  array('codigo' => '802','nombre' => 'SALAZAR','departamento' => '54'),
  array('codigo' => '803','nombre' => 'SALDAÑA','departamento' => '73'),
  array('codigo' => '804','nombre' => 'SALENTO','departamento' => '63'),
  array('codigo' => '805','nombre' => 'SALGAR','departamento' => '5'),
  array('codigo' => '806','nombre' => 'SAMACA','departamento' => '15'),
  array('codigo' => '807','nombre' => 'SAMANA','departamento' => '17'),
  array('codigo' => '808','nombre' => 'SAMANIEGO','departamento' => '52'),
  array('codigo' => '809','nombre' => 'SAMPUES','departamento' => '70'),
  array('codigo' => '810','nombre' => 'SAN AGUSTIN','departamento' => '41'),
  array('codigo' => '811','nombre' => 'SAN ALBERTO','departamento' => '20'),
  array('codigo' => '812','nombre' => 'SAN ANDRES','departamento' => '68'),
  array('codigo' => '813','nombre' => 'SAN ANDRES','departamento' => '88'),
  array('codigo' => '814','nombre' => 'SAN ANDRES DE CUERQUIA','departamento' => '5'),
  array('codigo' => '815','nombre' => 'SAN ANDRES DE TUMACO','departamento' => '52'),
  array('codigo' => '816','nombre' => 'SAN ANDRES SOTAVENTO','departamento' => '23'),
  array('codigo' => '817','nombre' => 'SAN ANTERO','departamento' => '23'),
  array('codigo' => '818','nombre' => 'SAN ANTONIO','departamento' => '73'),
  array('codigo' => '819','nombre' => 'SAN ANTONIO DEL TEQUENDAMA','departamento' => '25'),
  array('codigo' => '820','nombre' => 'SAN BENITO','departamento' => '68'),
  array('codigo' => '821','nombre' => 'SAN BENITO ABAD','departamento' => '70'),
  array('codigo' => '822','nombre' => 'SAN BERNARDO','departamento' => '25'),
  array('codigo' => '823','nombre' => 'SAN BERNARDO','departamento' => '52'),
  array('codigo' => '824','nombre' => 'SAN BERNARDO DEL VIENTO','departamento' => '23'),
  array('codigo' => '825','nombre' => 'SAN CALIXTO','departamento' => '54'),
  array('codigo' => '826','nombre' => 'SAN CARLOS','departamento' => '5'),
  array('codigo' => '827','nombre' => 'SAN CARLOS','departamento' => '23'),
  array('codigo' => '828','nombre' => 'SAN CARLOS DE GUAROA','departamento' => '50'),
  array('codigo' => '829','nombre' => 'SAN CAYETANO','departamento' => '25'),
  array('codigo' => '830','nombre' => 'SAN CAYETANO','departamento' => '54'),
  array('codigo' => '831','nombre' => 'SAN CRISTOBAL','departamento' => '13'),
  array('codigo' => '832','nombre' => 'SAN DIEGO','departamento' => '20'),
  array('codigo' => '833','nombre' => 'SAN EDUARDO','departamento' => '15'),
  array('codigo' => '834','nombre' => 'SAN ESTANISLAO','departamento' => '13'),
  array('codigo' => '835','nombre' => 'SAN FELIPE','departamento' => '94'),
  array('codigo' => '836','nombre' => 'SAN FERNANDO','departamento' => '13'),
  array('codigo' => '837','nombre' => 'SAN FRANCISCO','departamento' => '5'),
  array('codigo' => '838','nombre' => 'SAN FRANCISCO','departamento' => '25'),
  array('codigo' => '839','nombre' => 'SAN FRANCISCO','departamento' => '86'),
  array('codigo' => '840','nombre' => 'SAN GIL','departamento' => '68'),
  array('codigo' => '841','nombre' => 'SAN JACINTO','departamento' => '13'),
  array('codigo' => '842','nombre' => 'SAN JACINTO DEL CAUCA','departamento' => '13'),
  array('codigo' => '843','nombre' => 'SAN JERONIMO','departamento' => '5'),
  array('codigo' => '844','nombre' => 'SAN JOAQUIN','departamento' => '68'),
  array('codigo' => '845','nombre' => 'SAN JOSE','departamento' => '17'),
  array('codigo' => '846','nombre' => 'SAN JOSE DE LA MONTAÑA','departamento' => '5'),
  array('codigo' => '847','nombre' => 'SAN JOSE DE MIRANDA','departamento' => '68'),
  array('codigo' => '848','nombre' => 'SAN JOSE DE PARE','departamento' => '15'),
  array('codigo' => '849','nombre' => 'SAN JOSE DEL FRAGUA','departamento' => '18'),
  array('codigo' => '850','nombre' => 'SAN JOSE DEL GUAVIARE','departamento' => '95'),
  array('codigo' => '851','nombre' => 'SAN JOSE DEL PALMAR','departamento' => '27'),
  array('codigo' => '852','nombre' => 'SAN JUAN DE ARAMA','departamento' => '50'),
  array('codigo' => '853','nombre' => 'SAN JUAN DE BETULIA','departamento' => '70'),
  array('codigo' => '854','nombre' => 'SAN JUAN DE RIO SECO','departamento' => '25'),
  array('codigo' => '855','nombre' => 'SAN JUAN DE URABA','departamento' => '5'),
  array('codigo' => '856','nombre' => 'SAN JUAN DEL CESAR','departamento' => '44'),
  array('codigo' => '857','nombre' => 'SAN JUAN NEPOMUCENO','departamento' => '13'),
  array('codigo' => '858','nombre' => 'SAN JUANITO','departamento' => '50'),
  array('codigo' => '859','nombre' => 'SAN LORENZO','departamento' => '52'),
  array('codigo' => '860','nombre' => 'SAN LUIS','departamento' => '5'),
  array('codigo' => '861','nombre' => 'SAN LUIS','departamento' => '73'),
  array('codigo' => '862','nombre' => 'SAN LUIS DE GACENO','departamento' => '15'),
  array('codigo' => '863','nombre' => 'SAN LUIS DE PALENQUE','departamento' => '85'),
  array('codigo' => '864','nombre' => 'SAN LUIS DE SINCE','departamento' => '70'),
  array('codigo' => '865','nombre' => 'SAN MARCOS','departamento' => '70'),
  array('codigo' => '866','nombre' => 'SAN MARTIN','departamento' => '20'),
  array('codigo' => '867','nombre' => 'SAN MARTIN','departamento' => '50'),
  array('codigo' => '868','nombre' => 'SAN MARTIN DE LOBA','departamento' => '13'),
  array('codigo' => '869','nombre' => 'SAN MATEO','departamento' => '15'),
  array('codigo' => '870','nombre' => 'SAN MIGUEL','departamento' => '68'),
  array('codigo' => '871','nombre' => 'SAN MIGUEL','departamento' => '86'),
  array('codigo' => '872','nombre' => 'SAN MIGUEL DE SEMA','departamento' => '15'),
  array('codigo' => '873','nombre' => 'SAN ONOFRE','departamento' => '70'),
  array('codigo' => '874','nombre' => 'SAN PABLO','departamento' => '13'),
  array('codigo' => '875','nombre' => 'SAN PABLO','departamento' => '52'),
  array('codigo' => '876','nombre' => 'SAN PABLO DE BORBUR','departamento' => '15'),
  array('codigo' => '877','nombre' => 'SAN PEDRO','departamento' => '5'),
  array('codigo' => '878','nombre' => 'SAN PEDRO','departamento' => '70'),
  array('codigo' => '879','nombre' => 'SAN PEDRO','departamento' => '76'),
  array('codigo' => '880','nombre' => 'SAN PEDRO DE CARTAGO','departamento' => '52'),
  array('codigo' => '881','nombre' => 'SAN PEDRO DE URABA','departamento' => '5'),
  array('codigo' => '882','nombre' => 'SAN PELAYO','departamento' => '23'),
  array('codigo' => '883','nombre' => 'SAN RAFAEL','departamento' => '5'),
  array('codigo' => '884','nombre' => 'SAN ROQUE','departamento' => '5'),
  array('codigo' => '885','nombre' => 'SAN SEBASTIAN','departamento' => '19'),
  array('codigo' => '886','nombre' => 'SAN SEBASTIAN DE BUENAVISTA','departamento' => '47'),
  array('codigo' => '887','nombre' => 'SAN VICENTE','departamento' => '5'),
  array('codigo' => '888','nombre' => 'SAN VICENTE DE CHUCURI','departamento' => '68'),
  array('codigo' => '889','nombre' => 'SAN VICENTE DEL CAGUAN','departamento' => '18'),
  array('codigo' => '890','nombre' => 'SAN ZENON','departamento' => '47'),
  array('codigo' => '891','nombre' => 'SANDONA','departamento' => '52'),
  array('codigo' => '892','nombre' => 'SANTA ANA','departamento' => '47'),
  array('codigo' => '893','nombre' => 'SANTA BARBARA','departamento' => '5'),
  array('codigo' => '894','nombre' => 'SANTA BARBARA','departamento' => '52'),
  array('codigo' => '895','nombre' => 'SANTA BARBARA','departamento' => '68'),
  array('codigo' => '896','nombre' => 'SANTA BARBARA DE PINTO','departamento' => '47'),
  array('codigo' => '897','nombre' => 'SANTA CATALINA','departamento' => '13'),
  array('codigo' => '898','nombre' => 'SANTA HELENA DEL OPON','departamento' => '68'),
  array('codigo' => '899','nombre' => 'SANTA ISABEL','departamento' => '73'),
  array('codigo' => '900','nombre' => 'SANTA LUCIA','departamento' => '8'),
  array('codigo' => '901','nombre' => 'SANTA MARIA','departamento' => '15'),
  array('codigo' => '902','nombre' => 'SANTA MARIA','departamento' => '41'),
  array('codigo' => '903','nombre' => 'SANTA MARTA','departamento' => '47'),
  array('codigo' => '904','nombre' => 'SANTA ROSA','departamento' => '13'),
  array('codigo' => '905','nombre' => 'SANTA ROSA','departamento' => '19'),
  array('codigo' => '906','nombre' => 'SANTA ROSA DE CABAL','departamento' => '66'),
  array('codigo' => '907','nombre' => 'SANTA ROSA DE OSOS','departamento' => '5'),
  array('codigo' => '908','nombre' => 'SANTA ROSA DE VITERBO','departamento' => '15'),
  array('codigo' => '909','nombre' => 'SANTA ROSA DEL SUR','departamento' => '13'),
  array('codigo' => '910','nombre' => 'SANTA ROSALIA','departamento' => '99'),
  array('codigo' => '911','nombre' => 'SANTA SOFIA','departamento' => '15'),
  array('codigo' => '912','nombre' => 'SANTACRUZ','departamento' => '52'),
  array('codigo' => '913','nombre' => 'SANTAFE DE ANTIOQUIA','departamento' => '5'),
  array('codigo' => '914','nombre' => 'SANTANA','departamento' => '15'),
  array('codigo' => '915','nombre' => 'SANTANDER DE QUILICHAO','departamento' => '19'),
  array('codigo' => '916','nombre' => 'SANTIAGO','departamento' => '54'),
  array('codigo' => '917','nombre' => 'SANTIAGO','departamento' => '86'),
  array('codigo' => '918','nombre' => 'SANTIAGO DE TOLU','departamento' => '70'),
  array('codigo' => '919','nombre' => 'SANTO DOMINGO','departamento' => '5'),
  array('codigo' => '920','nombre' => 'SANTO TOMAS','departamento' => '8'),
  array('codigo' => '921','nombre' => 'SANTUARIO','departamento' => '66'),
  array('codigo' => '922','nombre' => 'SAPUYES','departamento' => '52'),
  array('codigo' => '923','nombre' => 'SARAVENA','departamento' => '81'),
  array('codigo' => '924','nombre' => 'SARDINATA','departamento' => '54'),
  array('codigo' => '925','nombre' => 'SASAIMA','departamento' => '25'),
  array('codigo' => '926','nombre' => 'SATIVANORTE','departamento' => '15'),
  array('codigo' => '927','nombre' => 'SATIVASUR','departamento' => '15'),
  array('codigo' => '928','nombre' => 'SEGOVIA','departamento' => '5'),
  array('codigo' => '929','nombre' => 'SESQUILE','departamento' => '25'),
  array('codigo' => '930','nombre' => 'SEVILLA','departamento' => '76'),
  array('codigo' => '931','nombre' => 'SIACHOQUE','departamento' => '15'),
  array('codigo' => '932','nombre' => 'SIBATE','departamento' => '25'),
  array('codigo' => '933','nombre' => 'SIBUNDOY','departamento' => '86'),
  array('codigo' => '934','nombre' => 'SILOS','departamento' => '54'),
  array('codigo' => '935','nombre' => 'SILVANIA','departamento' => '25'),
  array('codigo' => '936','nombre' => 'SILVIA','departamento' => '19'),
  array('codigo' => '937','nombre' => 'SIMACOTA','departamento' => '68'),
  array('codigo' => '938','nombre' => 'SIMIJACA','departamento' => '25'),
  array('codigo' => '939','nombre' => 'SIMITI','departamento' => '13'),
  array('codigo' => '940','nombre' => 'SINCELEJO','departamento' => '70'),
  array('codigo' => '941','nombre' => 'SIPI','departamento' => '27'),
  array('codigo' => '942','nombre' => 'SITIONUEVO','departamento' => '47'),
  array('codigo' => '943','nombre' => 'SOACHA','departamento' => '25'),
  array('codigo' => '944','nombre' => 'SOATA','departamento' => '15'),
  array('codigo' => '945','nombre' => 'SOCHA','departamento' => '15'),
  array('codigo' => '946','nombre' => 'SOCORRO','departamento' => '68'),
  array('codigo' => '947','nombre' => 'SOCOTA','departamento' => '15'),
  array('codigo' => '948','nombre' => 'SOGAMOSO','departamento' => '15'),
  array('codigo' => '949','nombre' => 'SOLANO','departamento' => '18'),
  array('codigo' => '950','nombre' => 'SOLEDAD','departamento' => '8'),
  array('codigo' => '951','nombre' => 'SOLITA','departamento' => '18'),
  array('codigo' => '952','nombre' => 'SOMONDOCO','departamento' => '15'),
  array('codigo' => '953','nombre' => 'SONSON','departamento' => '5'),
  array('codigo' => '954','nombre' => 'SOPETRAN','departamento' => '5'),
  array('codigo' => '955','nombre' => 'SOPLAVIENTO','departamento' => '13'),
  array('codigo' => '956','nombre' => 'SOPO','departamento' => '25'),
  array('codigo' => '957','nombre' => 'SORA','departamento' => '15'),
  array('codigo' => '958','nombre' => 'SORACA','departamento' => '15'),
  array('codigo' => '959','nombre' => 'SOTAQUIRA','departamento' => '15'),
  array('codigo' => '960','nombre' => 'SOTARA','departamento' => '19'),
  array('codigo' => '961','nombre' => 'SUAITA','departamento' => '68'),
  array('codigo' => '962','nombre' => 'SUAN','departamento' => '8'),
  array('codigo' => '963','nombre' => 'SUAREZ','departamento' => '19'),
  array('codigo' => '964','nombre' => 'SUAREZ','departamento' => '73'),
  array('codigo' => '965','nombre' => 'SUAZA','departamento' => '41'),
  array('codigo' => '966','nombre' => 'SUBACHOQUE','departamento' => '25'),
  array('codigo' => '967','nombre' => 'SUCRE','departamento' => '19'),
  array('codigo' => '968','nombre' => 'SUCRE','departamento' => '68'),
  array('codigo' => '969','nombre' => 'SUCRE','departamento' => '70'),
  array('codigo' => '970','nombre' => 'SUESCA','departamento' => '25'),
  array('codigo' => '971','nombre' => 'SUPATA','departamento' => '25'),
  array('codigo' => '972','nombre' => 'SUPIA','departamento' => '17'),
  array('codigo' => '973','nombre' => 'SURATA','departamento' => '68'),
  array('codigo' => '974','nombre' => 'SUSA','departamento' => '25'),
  array('codigo' => '975','nombre' => 'SUSACON','departamento' => '15'),
  array('codigo' => '976','nombre' => 'SUTAMARCHAN','departamento' => '15'),
  array('codigo' => '977','nombre' => 'SUTATAUSA','departamento' => '25'),
  array('codigo' => '978','nombre' => 'SUTATENZA','departamento' => '15'),
  array('codigo' => '979','nombre' => 'TABIO','departamento' => '25'),
  array('codigo' => '980','nombre' => 'TADO','departamento' => '27'),
  array('codigo' => '981','nombre' => 'TALAIGUA NUEVO','departamento' => '13'),
  array('codigo' => '982','nombre' => 'TAMALAMEQUE','departamento' => '20'),
  array('codigo' => '983','nombre' => 'TAMARA','departamento' => '85'),
  array('codigo' => '984','nombre' => 'TAME','departamento' => '81'),
  array('codigo' => '985','nombre' => 'TAMESIS','departamento' => '5'),
  array('codigo' => '986','nombre' => 'TAMINANGO','departamento' => '52'),
  array('codigo' => '987','nombre' => 'TANGUA','departamento' => '52'),
  array('codigo' => '988','nombre' => 'TARAIRA','departamento' => '97'),
  array('codigo' => '989','nombre' => 'TARAPACA','departamento' => '91'),
  array('codigo' => '990','nombre' => 'TARAZA','departamento' => '5'),
  array('codigo' => '991','nombre' => 'TARQUI','departamento' => '41'),
  array('codigo' => '992','nombre' => 'TARSO','departamento' => '5'),
  array('codigo' => '993','nombre' => 'TASCO','departamento' => '15'),
  array('codigo' => '994','nombre' => 'TAURAMENA','departamento' => '85'),
  array('codigo' => '995','nombre' => 'TAUSA','departamento' => '25'),
  array('codigo' => '996','nombre' => 'TELLO','departamento' => '41'),
  array('codigo' => '997','nombre' => 'TENA','departamento' => '25'),
  array('codigo' => '998','nombre' => 'TENERIFE','departamento' => '47'),
  array('codigo' => '999','nombre' => 'TENJO','departamento' => '25'),
  array('codigo' => '1000','nombre' => 'TENZA','departamento' => '15'),
  array('codigo' => '1001','nombre' => 'TEORAMA','departamento' => '54'),
  array('codigo' => '1002','nombre' => 'TERUEL','departamento' => '41'),
  array('codigo' => '1003','nombre' => 'TESALIA','departamento' => '41'),
  array('codigo' => '1004','nombre' => 'TIBACUY','departamento' => '25'),
  array('codigo' => '1005','nombre' => 'TIBANA','departamento' => '15'),
  array('codigo' => '1006','nombre' => 'TIBASOSA','departamento' => '15'),
  array('codigo' => '1007','nombre' => 'TIBIRITA','departamento' => '25'),
  array('codigo' => '1008','nombre' => 'TIBU','departamento' => '54'),
  array('codigo' => '1009','nombre' => 'TIERRALTA','departamento' => '23'),
  array('codigo' => '1010','nombre' => 'TIMANA','departamento' => '41'),
  array('codigo' => '1011','nombre' => 'TIMBIO','departamento' => '19'),
  array('codigo' => '1012','nombre' => 'TIMBIQUI','departamento' => '19'),
  array('codigo' => '1013','nombre' => 'TINJACA','departamento' => '15'),
  array('codigo' => '1014','nombre' => 'TIPACOQUE','departamento' => '15'),
  array('codigo' => '1015','nombre' => 'TIQUISIO','departamento' => '13'),
  array('codigo' => '1016','nombre' => 'TITIRIBI','departamento' => '5'),
  array('codigo' => '1017','nombre' => 'TOCA','departamento' => '15'),
  array('codigo' => '1018','nombre' => 'TOCAIMA','departamento' => '25'),
  array('codigo' => '1019','nombre' => 'TOCANCIPA','departamento' => '25'),
  array('codigo' => '1020','nombre' => 'TOGsI','departamento' => '15'),
  array('codigo' => '1021','nombre' => 'TOLEDO','departamento' => '5'),
  array('codigo' => '1022','nombre' => 'TOLEDO','departamento' => '54'),
  array('codigo' => '1023','nombre' => 'TOLU VIEJO','departamento' => '70'),
  array('codigo' => '1024','nombre' => 'TONA','departamento' => '68'),
  array('codigo' => '1025','nombre' => 'TOPAGA','departamento' => '15'),
  array('codigo' => '1026','nombre' => 'TOPAIPI','departamento' => '25'),
  array('codigo' => '1027','nombre' => 'TORIBIO','departamento' => '19'),
  array('codigo' => '1028','nombre' => 'TORO','departamento' => '76'),
  array('codigo' => '1029','nombre' => 'TOTA','departamento' => '15'),
  array('codigo' => '1030','nombre' => 'TOTORO','departamento' => '19'),
  array('codigo' => '1031','nombre' => 'TRINIDAD','departamento' => '85'),
  array('codigo' => '1032','nombre' => 'TRUJILLO','departamento' => '76'),
  array('codigo' => '1033','nombre' => 'TUBARA','departamento' => '8'),
  array('codigo' => '1034','nombre' => 'TULUA','departamento' => '76'),
  array('codigo' => '1035','nombre' => 'TUNJA','departamento' => '15'),
  array('codigo' => '1036','nombre' => 'TUNUNGUA','departamento' => '15'),
  array('codigo' => '1037','nombre' => 'TUQUERRES','departamento' => '52'),
  array('codigo' => '1038','nombre' => 'TURBACO','departamento' => '13'),
  array('codigo' => '1039','nombre' => 'TURBANA','departamento' => '13'),
  array('codigo' => '1040','nombre' => 'TURBO','departamento' => '5'),
  array('codigo' => '1041','nombre' => 'TURMEQUE','departamento' => '15'),
  array('codigo' => '1042','nombre' => 'TUTA','departamento' => '15'),
  array('codigo' => '1043','nombre' => 'TUTAZA','departamento' => '15'),
  array('codigo' => '1044','nombre' => 'UBALA','departamento' => '25'),
  array('codigo' => '1045','nombre' => 'UBAQUE','departamento' => '25'),
  array('codigo' => '1046','nombre' => 'ULLOA','departamento' => '76'),
  array('codigo' => '1047','nombre' => 'UMBITA','departamento' => '15'),
  array('codigo' => '1048','nombre' => 'UNE','departamento' => '25'),
  array('codigo' => '1049','nombre' => 'UNGUIA','departamento' => '27'),
  array('codigo' => '1050','nombre' => 'UNION PANAMERICANA','departamento' => '27'),
  array('codigo' => '1051','nombre' => 'URAMITA','departamento' => '5'),
  array('codigo' => '1052','nombre' => 'URIBE','departamento' => '50'),
  array('codigo' => '1053','nombre' => 'URIBIA','departamento' => '44'),
  array('codigo' => '1054','nombre' => 'URRAO','departamento' => '5'),
  array('codigo' => '1055','nombre' => 'URUMITA','departamento' => '44'),
  array('codigo' => '1056','nombre' => 'USIACURI','departamento' => '8'),
  array('codigo' => '1057','nombre' => 'UTICA','departamento' => '25'),
  array('codigo' => '1058','nombre' => 'VALDIVIA','departamento' => '5'),
  array('codigo' => '1059','nombre' => 'VALENCIA','departamento' => '23'),
  array('codigo' => '1060','nombre' => 'VALLE DE SAN JOSE','departamento' => '68'),
  array('codigo' => '1061','nombre' => 'VALLE DE SAN JUAN','departamento' => '73'),
  array('codigo' => '1062','nombre' => 'VALLE DEL GUAMUEZ','departamento' => '86'),
  array('codigo' => '1063','nombre' => 'VALLEDUPAR','departamento' => '20'),
  array('codigo' => '1064','nombre' => 'VALPARAISO','departamento' => '5'),
  array('codigo' => '1065','nombre' => 'VALPARAISO','departamento' => '18'),
  array('codigo' => '1066','nombre' => 'VEGACHI','departamento' => '5'),
  array('codigo' => '1067','nombre' => 'VELEZ','departamento' => '68'),
  array('codigo' => '1068','nombre' => 'VENADILLO','departamento' => '73'),
  array('codigo' => '1069','nombre' => 'VENECIA','departamento' => '5'),
  array('codigo' => '1070','nombre' => 'VENECIA','departamento' => '25'),
  array('codigo' => '1071','nombre' => 'VENTAQUEMADA','departamento' => '15'),
  array('codigo' => '1072','nombre' => 'VERGARA','departamento' => '25'),
  array('codigo' => '1073','nombre' => 'VERSALLES','departamento' => '76'),
  array('codigo' => '1074','nombre' => 'VETAS','departamento' => '68'),
  array('codigo' => '1075','nombre' => 'VIANI','departamento' => '25'),
  array('codigo' => '1076','nombre' => 'VICTORIA','departamento' => '17'),
  array('codigo' => '1077','nombre' => 'VIGIA DEL FUERTE','departamento' => '5'),
  array('codigo' => '1078','nombre' => 'VIJES','departamento' => '76'),
  array('codigo' => '1079','nombre' => 'VILLA CARO','departamento' => '54'),
  array('codigo' => '1080','nombre' => 'VILLA DE LEYVA','departamento' => '15'),
  array('codigo' => '1081','nombre' => 'VILLA DE SAN DIEGO DE UBATE','departamento' => '25'),
  array('codigo' => '1082','nombre' => 'VILLA DEL ROSARIO','departamento' => '54'),
  array('codigo' => '1083','nombre' => 'VILLA RICA','departamento' => '19'),
  array('codigo' => '1084','nombre' => 'VILLAGARZON','departamento' => '86'),
  array('codigo' => '1085','nombre' => 'VILLAGOMEZ','departamento' => '25'),
  array('codigo' => '1086','nombre' => 'VILLAHERMOSA','departamento' => '73'),
  array('codigo' => '1087','nombre' => 'VILLAMARIA','departamento' => '17'),
  array('codigo' => '1088','nombre' => 'VILLANUEVA','departamento' => '13'),
  array('codigo' => '1089','nombre' => 'VILLANUEVA','departamento' => '44'),
  array('codigo' => '1090','nombre' => 'VILLANUEVA','departamento' => '68'),
  array('codigo' => '1091','nombre' => 'VILLANUEVA','departamento' => '85'),
  array('codigo' => '1092','nombre' => 'VILLAPINZON','departamento' => '25'),
  array('codigo' => '1093','nombre' => 'VILLARRICA','departamento' => '73'),
  array('codigo' => '1094','nombre' => 'VILLAVICENCIO','departamento' => '50'),
  array('codigo' => '1095','nombre' => 'VILLAVIEJA','departamento' => '41'),
  array('codigo' => '1096','nombre' => 'VILLETA','departamento' => '25'),
  array('codigo' => '1097','nombre' => 'VIOTA','departamento' => '25'),
  array('codigo' => '1098','nombre' => 'VIRACACHA','departamento' => '15'),
  array('codigo' => '1099','nombre' => 'VISTAHERMOSA','departamento' => '50'),
  array('codigo' => '1100','nombre' => 'VITERBO','departamento' => '17'),
  array('codigo' => '1101','nombre' => 'YACOPI','departamento' => '25'),
  array('codigo' => '1102','nombre' => 'YACUANQUER','departamento' => '52'),
  array('codigo' => '1103','nombre' => 'YAGUARA','departamento' => '41'),
  array('codigo' => '1104','nombre' => 'YALI','departamento' => '5'),
  array('codigo' => '1105','nombre' => 'YARUMAL','departamento' => '5'),
  array('codigo' => '1106','nombre' => 'YAVARATE','departamento' => '97'),
  array('codigo' => '1107','nombre' => 'YOLOMBO','departamento' => '5'),
  array('codigo' => '1108','nombre' => 'YONDO','departamento' => '5'),
  array('codigo' => '1109','nombre' => 'YOPAL','departamento' => '85'),
  array('codigo' => '1110','nombre' => 'YOTOCO','departamento' => '76'),
  array('codigo' => '1111','nombre' => 'YUMBO','departamento' => '76'),
  array('codigo' => '1112','nombre' => 'ZAMBRANO','departamento' => '13'),
  array('codigo' => '1113','nombre' => 'ZAPATOCA','departamento' => '68'),
  array('codigo' => '1114','nombre' => 'ZAPAYAN','departamento' => '47'),
  array('codigo' => '1115','nombre' => 'ZARAGOZA','departamento' => '5'),
  array('codigo' => '1116','nombre' => 'ZARZAL','departamento' => '76'),
  array('codigo' => '1117','nombre' => 'ZETAQUIRA','departamento' => '15'),
  array('codigo' => '1118','nombre' => 'ZIPACON','departamento' => '25'),
  array('codigo' => '1119','nombre' => 'ZIPAQUIRA','departamento' => '25'),
  array('codigo' => '1120','nombre' => 'ZONA BANANERA','departamento' => '47'),
  array('codigo' => '1200','nombre' => 'TUMACO','departamento' => '52')
);
$departamento = array(
  array('codigo' => '5','nombre' => 'ANTIOQUIA','region' => '2'),
  array('codigo' => '8','nombre' => 'ATLANTICO','region' => '3'),
  array('codigo' => '11','nombre' => 'BOGOTA','region' => '4'),
  array('codigo' => '13','nombre' => 'BOLIVAR','region' => '3'),
  array('codigo' => '15','nombre' => 'BOYACA','region' => '4'),
  array('codigo' => '17','nombre' => 'CALDAS','region' => '2'),
  array('codigo' => '18','nombre' => 'CAQUETA','region' => '1'),
  array('codigo' => '19','nombre' => 'CAUCA','region' => '6'),
  array('codigo' => '20','nombre' => 'CESAR','region' => '3'),
  array('codigo' => '23','nombre' => 'CORDOBA','region' => '3'),
  array('codigo' => '25','nombre' => 'CUNDINAMARCA','region' => '4'),
  array('codigo' => '27','nombre' => 'CHOCO','region' => '6'),
  array('codigo' => '41','nombre' => 'HUILA','region' => '4'),
  array('codigo' => '44','nombre' => 'LA GUAJIRA','region' => '3'),
  array('codigo' => '47','nombre' => 'MAGDALENA','region' => '3'),
  array('codigo' => '50','nombre' => 'META','region' => '4'),
  array('codigo' => '52','nombre' => 'NARIÑO','region' => '6'),
  array('codigo' => '54','nombre' => 'N. DE SANTANDER','region' => '7'),
  array('codigo' => '63','nombre' => 'QUINDIO','region' => '2'),
  array('codigo' => '66','nombre' => 'RISARALDA','region' => '2'),
  array('codigo' => '68','nombre' => 'SANTANDER','region' => '7'),
  array('codigo' => '70','nombre' => 'SUCRE','region' => '3'),
  array('codigo' => '73','nombre' => 'TOLIMA','region' => '4'),
  array('codigo' => '76','nombre' => 'VALLE DEL CAUCA','region' => '6'),
  array('codigo' => '81','nombre' => 'ARAUCA','region' => '5'),
  array('codigo' => '85','nombre' => 'CASANARE','region' => '5'),
  array('codigo' => '86','nombre' => 'PUTUMAYO','region' => '1'),
  array('codigo' => '88','nombre' => 'SAN ANDRES','region' => '3'),
  array('codigo' => '91','nombre' => 'AMAZONAS','region' => '1'),
  array('codigo' => '94','nombre' => 'GUAINIA','region' => '1'),
  array('codigo' => '95','nombre' => 'GUAVIARE','region' => '1'),
  array('codigo' => '97','nombre' => 'VAUPES','region' => '1'),
  array('codigo' => '99','nombre' => 'VICHADA','region' => '5')
);

if(isset($_GET['lc']))
{
foreach($ciudad as $valor) {    
echo "<option value='".$valor['codigo']."'>". $valor['nombre'] ."</option>";
 }
}
if(isset($_GET['ld']))
{
foreach($departamento as $valor) {    
echo "<option value='".$valor['codigo']."'>". $valor['nombre'] ."</option>";
 }
}
 function listarDep(){
   global $departamento;
foreach($departamento as $valor) {    
echo "<option value='".$valor['codigo']."'>". $valor['nombre'] ."</option>";
 }
}
function listarCiu(){
 global $ciudad;
foreach($ciudad  as $valor) {    
echo "<option value='".$valor['codigo']."'>". $valor['nombre'] ."</option>";
 }}
?>
